In [1]:
import numpy as np
import pandas as pd
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data.csv")

In [2]:
print(data.columns)
pd.set_option("display.max_columns",None)

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'opponent_avg_points', 'venue_avg_points',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'player_role_wicketkeeper', 'team_won_toss',
       'recent_form', 'venue_form', 'team_Deccan Chargers',
       'team_Delhi Capitals', 'team_Gujarat Lions', 'team_Gujarat Titans',
       'team_Kochi Tuskers Kerala', 'team_Kolkata Knight Riders',
       'team_Lucknow Super Giants', 'team_Mumbai Indians',
       'team_Pune Warriors', 'team_Punjab Kings', 'team_Rajasthan Royals',
       'team_Rising Pune Supergiants', 'team_Royal Challengers Bengaluru',
       'team_Sunrisers Hyderabad', 'opponent_Deccan Chargers',
       'opponent_Delhi Capitals', 'opponent_Gujarat Lions',
       'opponent_Gujarat Titans', 'opponent_Kochi Tuskers Kerala',
       'opponent_Kolkata Knight Riders', 'opponent_Lucknow Super Giants',
       'opponent_Mumbai Indians', 'opponent_Pune Warriors',
       'opponent_Punjab Kings', 'opponent_Rajasthan Royals',
       'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler'],
      dtype='object')

In [3]:
import joblib

model = joblib.load("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/models/point_predicter.pkl")

In [4]:
team1 = "Chennai Super Kings"
team2 = "Mumbai Indians"

venue = "Wankhede Stadium"
team1_squad =  [
    'MS Dhoni','Ravindra Jadeja','Ruturaj Gaikwad','Deepak Chahar','Moeen Ali',
'Shivam Dube','Matheesha Pathirana','Ajinkya Rahane','Daryl Mitchell',
'Mitchell Santner','Tushar Deshpande'
]
team2_squad = ['Rohit Sharma','Ishan Kishan','Suryakumar Yadav','Hardik Pandya',
'Tim David','Jasprit Bumrah','Piyush Chawla','Tilak Varma',
'Gerald Coetzee','Romario Shepherd','Nehal Wadhera'
]
squad = team1_squad+team2_squad

In [5]:
historical_data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/historical_data.csv")
historical_data['pitch_type'] = historical_data['pitch_type'].fillna('balanced')

In [6]:
historical_data.columns

Index(['match_id', 'player', 'fantasy_points', 'team', 'opponent', 'venue',
       'toss_decision', 'stage', 'season', 'player_match_number',
       'last3_avg_points', 'last5_avg_points', 'last10_avg_points',
       'rolling_strike_rate', 'rolling_wickets', 'opponent_avg_points',
       'pitch_type', 'venue_avg_points', 'venue_run_factor',
       'batting_contribution_ratio', 'bowling_contribution_ratio',
       'player_role', 'last10_std_points', 'player_consistency_index',
       'form_momentum', 'bat_pos', 'boundary_percentage', 'bat_pos_per_match',
       'player_role_wicketkeeper', 'match_month', 'team_won_toss',
       'recent_form', 'venue_form'],
      dtype='object')

In [7]:
colsToDrop =  ['last5_avg_points',
              'last10_avg_points',
              'bat_pos_per_match',
              'match_month',
              'stage'
              ]
historical_data = historical_data.drop(columns = colsToDrop)

In [8]:
from rapidfuzz import process
import re

def normalize_name(name):
    name = name.lower().strip()
    name = re.sub(r'[^a-z ]', '', name)
    name = re.sub(r'\s+', ' ', name)
    return name

# Normalize historical players
historical_data['player_key'] = historical_data['player'].apply(normalize_name)
data['player_key'] = data['player'].apply(normalize_name)
# Build player pool ONLY from squads
squad = team1_squad + team2_squad
squad_keys = {normalize_name(p): p for p in squad}

# Create reverse lookup from historical data
hist_key_to_name = dict(zip(historical_data['player_key'], historical_data['player']))

def resolve_initial(name, squad):
    parts = name.split()
    
    if len(parts) == 2 and len(parts[0]) == 1:
        initial, last = parts
        
        candidates = [
            p for p in squad
            if p.split()[-1].lower() == last.lower()
            and p[0].lower() == initial.lower()
        ]
        
        if len(candidates) == 1:
            return candidates[0]
    
    return None

def safe_map_player(name):
    name_norm = normalize_name(name)
    
    # 1️⃣ Exact match
    if name_norm in hist_key_to_name:
        return hist_key_to_name[name_norm]
    
    # 2️⃣ Initial resolution (R Sharma → Rohit Sharma)
    resolved = resolve_initial(name, squad)
    if resolved:
        resolved_norm = normalize_name(resolved)
        return hist_key_to_name.get(resolved_norm, resolved)
    
    # 3️⃣ Fuzzy match ONLY within squad
    match = process.extractOne(name, squad, score_cutoff=90)
    
    if match:
        matched_name = match[0]
        return hist_key_to_name.get(normalize_name(matched_name), matched_name)
    
    return None

In [9]:
data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,player_key
0,548341,A Ashish Reddy,58.0,Subrata Roy Sahara Stadium,2012,1,35.672040,80.762144,0.0,39.250000,58.00,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,2068.978308,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,a ashish reddy
1,548346,A Ashish Reddy,41.0,Wankhede Stadium,2012,2,35.672040,80.762144,0.0,30.000000,41.00,1.035196,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,0,0,35.672040,1462.553632,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,a ashish reddy
2,548348,A Ashish Reddy,23.0,Barabati Stadium,2012,3,35.672040,80.762144,0.0,39.250000,23.00,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,820.456915,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,a ashish reddy
3,548352,A Ashish Reddy,28.0,MA Chidambaram Stadium,2012,4,40.666667,80.762144,0.0,47.333333,45.00,0.984847,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,0,0,38.668816,1740.096716,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,a ashish reddy
4,548356,A Ashish Reddy,33.0,M Chinnaswamy Stadium,2012,5,30.666667,80.762144,0.0,38.714286,31.75,1.016059,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,0,0,32.668816,1037.234905,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,False,True,a ashish reddy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Rajiv Gandhi International Stadium,2025,6,3.333333,0.000000,0.8,18.500000,6.75,0.994802,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,0,0,13.247204,89.418627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,zeeshan ansari
25121,1473480,Zeeshan Ansari,0.0,MA Chidambaram Stadium,2025,7,11.666667,0.000000,0.4,0.000000,0.00,0.984847,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,0,1,14.647204,0.000000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,zeeshan ansari
25122,1473488,Zeeshan Ansari,23.0,Narendra Modi Stadium,2025,8,12.333333,0.000000,0.2,11.500000,23.00,1.079940,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,0,1,13.067204,300.545692,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,zeeshan ansari
25123,1473492,Zeeshan Ansari,4.0,Rajiv Gandhi International Stadium,2025,9,16.000000,0.000000,0.4,44.500000,6.75,0.994802,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,0,1,16.647204,112.368627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,zeeshan ansari
25124,1473499,Zeeshan Ansari,-2.0,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025,10,9.000000,0.000000,0.4,-2.000000,-2.00,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,0,1,12.807204,-25.614408,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,zeeshan ansari

In [13]:
historical_data

,match_id,player,fantasy_points,team,opponent,venue,toss_decision,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,player_key
0,548341,A Ashish Reddy,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,bat,2012,1,35.672040,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,2068.978308,a ashish reddy
1,548346,A Ashish Reddy,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,field,2012,2,35.672040,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,0,0,35.672040,1462.553632,a ashish reddy
2,548348,A Ashish Reddy,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,bat,2012,3,35.672040,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,0,1,35.672040,820.456915,a ashish reddy
3,548352,A Ashish Reddy,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,bat,2012,4,40.666667,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,0,0,38.668816,1740.096716,a ashish reddy
4,548356,A Ashish Reddy,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,field,2012,5,30.666667,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,0,0,32.668816,1037.234905,a ashish reddy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,field,2025,6,3.333333,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,0,0,13.247204,89.418627,zeeshan ansari
25121,1473480,Zeeshan Ansari,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,field,2025,7,11.666667,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,0,1,14.647204,0.000000,zeeshan ansari
25122,1473488,Zeeshan Ansari,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,field,2025,8,12.333333,0.000000,0.2,11.500000,balanced,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,0,1,13.067204,300.545692,zeeshan ansari
25123,1473492,Zeeshan Ansari,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,field,2025,9,16.000000,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,0,1,16.647204,112.368627,zeeshan ansari
25124,1473499,Zeeshan Ansari,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,field,2025,10,9.000000,0.000000,0.4,-2.000000,balanced,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,0,1,12.807204,-25.614408,zeeshan ansari

In [14]:
mapped_players_1 = [safe_map_player(p) for p in team1_squad]
mapped_players_2 = [safe_map_player(p) for p in team2_squad]
all_mapped = mapped_players_1 + mapped_players_2

unmatched = [p for p in squad if safe_map_player(p) is None]

if unmatched:
    print("⚠️ Unmatched players:", unmatched)

In [25]:
historical_data['player'].unique()

array(['A Ashish Reddy', 'A Badoni', 'A Chandila', 'A Chopra',
       'A Choudhary', 'A Dananjaya', 'A Flintoff', 'A Kamboj', 'A Kumble',
       'A Manohar', 'A Mhatre', 'A Mishra', 'A Mithun', 'A Mukund',
       'A Nehra', 'A Nel', 'A Nortje', 'A Raghuvanshi', 'A Singh',
       'A Symonds', 'A Tomar', 'A Uniyal', 'A Zampa', 'AA Bilakhia',
       'AA Chavan', 'AA Jhunjhunwala', 'AA Kazi', 'AA Kulkarni',
       'AA Noffke', 'AB Agarkar', 'AB Barath', 'AB Dinda', 'AB McDonald',
       'AB de Villiers', 'AC Blizzard', 'AC Gilchrist', 'AC Thomas',
       'AC Voges', 'AD Hales', 'AD Mascarenhas', 'AD Mathews', 'AD Nath',
       'AD Russell', 'AF Milne', 'AG Murtaza', 'AG Paunikar', 'AJ Finch',
       'AJ Hosein', 'AJ Turner', 'AJ Tye', 'AK Markram', 'AL Menaria',
       'AM Nayar', 'AM Rahane', 'AM Salvi', 'AN Ahmed', 'AN Ghosh',
       'AP Dole', 'AP Majumdar', 'AP Tare', 'AR Bawne', 'AR Patel',
       'AS Joseph', 'AS Rajpoot', 'AS Raut', 'AS Roy', 'AS Yadav',
       'AT Carey', 'AT Rayudu', 'AU Rashid', 'AUK Pathan', 'Abdul Basith',
       'Abdul Samad', 'Abdur Razzak', 'Abhishek Sharma', 'Abishek Porel',
       'Akash Deep', 'Akash Madhwal', 'Akash Singh', 'Aman Hakim Khan',
       'Anand Rajan', 'Aniket Verma', 'Anirudh Singh', 'Ankit Sharma',
       'Ankit Soni', 'Anmolpreet Singh', 'Anuj Rawat', 'Anureet Singh',
       'Arjun Tendulkar', 'Arshad Khan', 'Arshad Khan (2)',
       'Arshdeep Singh', 'Ashutosh Sharma', 'Ashwani Kumar',
       'Atharva Taide', 'Avesh Khan', 'Azhar Mahmood',
       'Azmatullah Omarzai', 'B Akhil', 'B Chipli', 'B Geeves',
       'B Indrajith', 'B Kumar', 'B Laughlin', 'B Lee', 'B Sai Sudharsan',
       'B Stanlake', 'B Sumanth', 'BA Bhatt', 'BA Stokes', 'BAW Mendis',
       'BB McCullum', 'BB Samantray', 'BB Sran', 'BCJ Cutting',
       'BE Hendricks', 'BJ Haddin', 'BJ Hodge', 'BJ Rohrer', 'BKG Mendis',
       'BMAJ Mendis', 'BR Dunk', 'BR Sharath', 'BW Hilfenhaus',
       'Basil Thampi', 'Bipul Sharma', 'C Bosch', 'C Ganapathy',
       'C Green', 'C Madan', 'C Munro', 'C Nanda', 'C Sakariya',
       'C de Grandhomme', 'CA Ingram', 'CA Lynn', 'CA Pujara', 'CH Gayle',
       'CH Morris', 'CJ Anderson', 'CJ Dala', 'CJ Ferguson', 'CJ Green',
       'CJ Jordan', 'CJ McKay', 'CK Kapugedera', 'CK Langeveldt',
       'CL White', 'CM Gautam', 'CR Brathwaite', 'CR Woakes',
       'CRD Fernando', 'CV Varun', 'D Brevis', 'D Ferreira', 'D Jansen',
       'D Kalyankrishna', 'D Padikkal', 'D Pretorius', 'D Salunkhe',
       'D Wiese', 'D du Preez', 'DA Miller', 'DA Warner', 'DAJ Bracewell',
       'DB Das', 'DB Ravi Teja', 'DE Bollinger', 'DG Nalkande',
       'DH Yagnik', 'DJ Bravo', 'DJ Harris', 'DJ Hooda', 'DJ Hussey',
       'DJ Jacobs', 'DJ Malan', 'DJ Mitchell', 'DJ Muthuswami',
       'DJ Thornely', 'DJ Willey', 'DJG Sammy', 'DJM Short', 'DL Chahar',
       'DL Vettori', 'DM Bravo', 'DNT Zoysa', 'DP Conway', 'DP Nannes',
       'DP Vijaykumar', 'DPMD Jayawardene', 'DR Martyn', 'DR Sams',
       'DR Shorey', 'DR Smith', 'DS Kulkarni', 'DS Lehmann', 'DS Rathi',
       'DT Christian', 'DT Patil', 'DW Steyn', 'Dhruv Jurel', 'E Lewis',
       'E Malinga', 'EJG Morgan', 'ER Dwivedi', 'F Behardien',
       'F du Plessis', 'FA Allen', 'FH Edwards', 'FY Fazal',
       'Fazalhaq Farooqi', 'G Coetzee', 'G Gambhir', 'GB Hogg',
       'GC Smith', 'GC Viljoen', 'GD McGrath', 'GD Phillips', 'GH Vihari',
       'GHS Garton', 'GJ Bailey', 'GJ Maxwell', 'GR Napier', 'GS Sandhu',
       'Gagandeep Singh', 'Gulbadin Naib', 'Gurkeerat Singh',
       'Gurnoor Brar', 'H Das', 'H Klaasen', 'H Sharma', 'HC Brook',
       'HE van der Dussen', 'HF Gurney', 'HH Gibbs', 'HH Pandya',
       'HM Amla', 'HR Shokeen', 'HV Patel', 'Harbhajan Singh',
       'Harmeet Singh', 'Harpreet Brar', 'Harpreet Singh', 'Harsh Dubey',
       'Harshit Rana', 'I Malhotra', 'I Sharma', 'I Udana', 'IC Pandey',
       'IC Porel', 'IK Pathan', 'IR Jaggi', 'IS Sodhi', 'Imran Tahir',
       'Iqbal Abdulla', 'Ishan Kishan', 'J Arunkumar', 'J Botha',
       'J Fraser-McGurk', 'J Little', 'J Overton', 'J Suchith',
       'J Syed Mohammad', 'J Theron', 'J Yadav', 'JA Morkel',
       'JA Richardson', 'JC Archer', 'JC Buttler', 'JD Ryder',
       'JD Unadkat', 'JDP Oram', 'JDS Neesham', 'JE Root', 'JE Taylor',
       'JEC Franklin', 'JG Bethell', 'JH Kallis', 'JJ Bumrah', 'JJ Roy',
       'JJ van der Wath', 'JL Denly', 'JL Pattinson', 'JM Bairstow',
       'JM Kemp', 'JM Sharma', 'JO Holder', 'JP Behrendorff', 'JP Duminy',
       'JP Faulkner', 'JP Inglis', 'JPR Scantlebury-Searles',
       'JR Hazlewood', 'JR Hopes', 'JR Philippe', 'JW Hastings',
       'Jalaj S Saxena', 'Jaskaran Singh', 'Joginder Sharma', 'K Goel',
       'K Gowtham', 'K Kartikeya', 'K Khejroliya', 'K Rabada',
       'K Santokie', 'K Upadhyay', 'K Yadav', 'KA Jamieson', 'KA Maharaj',
       'KA Pollard', 'KAJ Roach', 'KB Arun Karthik', 'KC Cariappa',
       'KC Sangakkara', 'KD Karthik', 'KH Pandya', 'KJ Abbott',
       'KK Ahmed', 'KK Cooper', 'KK Nair', 'KL Nagarkoti', 'KL Rahul',
       'KM Asif', 'KM Jadhav', 'KMA Paul', 'KMDN Kulasekara',
       'KP Appanna', 'KP Pietersen', 'KR Mayers', 'KR Sen', 'KS Bharat',
       'KS Rathore', 'KS Sharma', 'KS Williamson', 'KT Maphaka',
       'KV Sharma', 'KW Richardson', 'Kamran Akmal', 'Kamran Khan',
       'Karanveer Singh', 'Karim Janat', 'Kartik Tyagi', 'Kuldeep Yadav',
       'Kumar Kushagra', 'L Ablish', 'L Balaji', 'L Ngidi', 'L Ronchi',
       'L Wood', 'LA Carseldine', 'LA Pomersbach', 'LB Williams',
       'LE Plunkett', 'LH Ferguson', 'LI Meriwala', 'LJ Wright',
       'LMP Simmons', 'LPC Silva', 'LR Shukla', 'LRPL Taylor',
       'LS Livingstone', 'Lalit Yadav', 'Liton Das', 'M Ashwin',
       'M Jansen', 'M Kaif', 'M Kartik', 'M Klinger', 'M Manhas',
       'M Markande', 'M Morkel', 'M Muralitharan', 'M Ntini',
       'M Pathirana', 'M Prasidh Krishna', 'M Rawat', 'M Shahrukh Khan',
       'M Siddharth', 'M Theekshana', 'M Tiwari', 'M Vijay', 'M Vohra',
       'M de Lange', 'MA Agarwal', 'MA Khote', 'MA Starc', 'MA Wood',
       'MB Parmar', 'MC Henriques', 'MC Juneja', 'MD Mishra',
       'MD Shanaka', 'MDKJ Perera', 'MEK Hussey', 'MF Maharoof',
       'MG Bracewell', 'MG Johnson', 'MG Neser', 'MJ Clarke',
       'MJ Guptill', 'MJ Henry', 'MJ Lumb', 'MJ McClenaghan', 'MJ Owen',
       'MJ Santner', 'MJ Suthar', 'MK Lomror', 'MK Pandey', 'MK Tiwary',
       'ML Hayden', 'MM Ali', 'MM Patel', 'MM Sharma', 'MN Samuels',
       'MN van Wyk', 'MP Breetzke', 'MP Stoinis', 'MP Yadav', 'MR Marsh',
       'MS Bhandage', 'MS Bisla', 'MS Dhoni', 'MS Gony', 'MS Wade',
       'MV Boucher', 'MW Short', 'Mandeep Singh', 'Mashrafe Mortaza',
       'Mayank Dagar', 'Misbah-ul-Haq', 'Mohammad Ashraful',
       'Mohammad Asif', 'Mohammad Hafeez', 'Mohammad Nabi',
       'Mohammed Shami', 'Mohammed Siraj', 'Mohit Rathee', 'Mohsin Khan',
       'Monu Kumar', 'Mujeeb Ur Rahman', 'Mukesh Choudhary',
       'Mukesh Kumar', 'Musheer Khan', 'Mustafizur Rahman', 'N Burger',
       'N Jagadeesan', 'N Pooran', 'N Rana', 'N Saini', 'N Thushara',
       'N Wadhera', 'NA Saini', 'NB Singh', 'ND Doshi', 'NJ Maddinson',
       'NJ Rimmington', 'NK Patel', 'NL McCullum', 'NLTC Perera',
       'NM Coulter-Nile', 'NS Naik', 'NT Ellis', 'NV Ojha', 'Naman Dhir',
       'Navdeep Saini', 'Naveen-ul-Haq', 'Nithish Kumar Reddy',
       'Noor Ahmad', 'O Thomas', 'OA Shah', 'OC McCoy', 'OF Smith',
       'P Amarnath', 'P Awana', 'P Chopra', 'P Dogra', 'P Dubey',
       'P Kumar', 'P Negi', 'P Parameswaran', 'P Prasanth',
       'P Ray Barman', 'P Sahu', 'P Simran Singh', 'P Suyal', 'PA Patel',
       'PA Reddy', 'PBB Rajapaksa', 'PC Valthaty', 'PD Collingwood',
       'PD Salt', 'PH Solanki', 'PHKD Mendis', 'PJ Cummins', 'PJ Sangwan',
       'PK Garg', 'PM Sarvesh Kumar', 'PN Mankad', 'PP Chawla', 'PP Ojha',
       'PP Shaw', 'PR Shah', 'PSP Handscomb', 'PV Tambe', 'PVD Chameera',
       'PVSN Raju', 'PWA Mulder', 'PWH de Silva', 'Pankaj Singh',
       'Parvez Rasool', 'Prince Yadav', 'Priyansh Arya', 'Q de Kock',
       'R Ashwin', 'R Bhatia', 'R Bishnoi', 'R Dhawan', 'R Dravid',
       'R Goyal', 'R McLaren', 'R Minz', 'R Ninan', 'R Parag', 'R Powell',
       'R Rampaul', 'R Ravindra', 'R Sai Kishore', 'R Sanjay Yadav',
       'R Sathish', 'R Sharma', 'R Shepherd', 'R Shukla', 'R Tewatia',
       'R Vinay Kumar', 'RA Bawa', 'RA Jadeja', 'RA Shaikh',
       'RA Tripathi', 'RD Chahar', 'RD Gaikwad', 'RD Rickelton',
       'RE Levi', 'RE van der Merwe', 'RG More', 'RG Sharma',
       'RJ Gleeson', 'RJ Harris', 'RJ Peterson', 'RJ Quiney',
       'RJW Topley', 'RK Bhui', 'RK Singh', 'RM Patidar',
       'RN ten Doeschate', 'RP Meredith', 'RP Singh', 'RR Bhatkal',
       'RR Bose', 'RR Pant', 'RR Powar', 'RR Raje', 'RR Rossouw',
       'RR Sarwan', 'RS Bopara', 'RS Gavaskar', 'RS Hangargekar',
       'RS Sodhi', 'RT Ponting', 'RV Gomez', 'RV Patel', 'RV Uthappa',
       'RW Price', 'Rahmanullah Gurbaz', 'Ramandeep Singh', 'Rashid Khan',
       'Rasikh Salam', 'Ravi Bishnoi', 'S Anirudha', 'S Aravind',
       'S Badree', 'S Badrinath', 'S Chanderpaul', 'S Dhawan', 'S Dube',
       'S Gopal', 'S Joseph', 'S Kaul', 'S Kaushik', 'S Ladda',
       'S Lamichhane', 'S Midhun', 'S Nadeem', 'S Narwal', 'S Rana',
       'S Randiv', 'S Sandeep Warrier', 'S Sohal', 'S Sreesanth',
       'S Sriram', 'S Tyagi', 'S Vidyut', 'SA Abbott', 'SA Asnodkar',
       'SA Yadav', 'SB Bangar', 'SB Dubey', 'SB Jakati', 'SB Joshi',
       'SB Styris', 'SB Wagh', 'SC Ganguly', 'SC Kuggeleijn',
       'SD Chitnis', 'SD Hope', 'SD Lad', 'SE Bond', 'SE Marsh',
       'SE Rutherford', 'SH Johnson', 'SJ Srivastava', 'SK Raina',
       'SK Rasheed', 'SK Trivedi', 'SK Warne', 'SL Malinga', 'SM Boland',
       'SM Curran', 'SM Harwood', 'SM Katich', 'SM Pollock',
       'SMSM Senanayake', 'SN Khan', 'SN Thakur', 'SO Hetmyer',
       'SP Fleming', 'SP Goswami', 'SP Jackson', 'SP Narine', 'SPD Smith',
       'SR Tendulkar', 'SR Watson', 'SS Agarwal', 'SS Cottrell',
       'SS Iyer', 'SS Mundhe', 'SS Prabhudessai', 'SS Sarkar',
       'SS Shaikh', 'SS Tiwary', 'SSB Magala', 'ST Jayasuriya',
       'STR Binny', 'SV Samson', 'SW Billings', 'SW Tait', 'SZ Mulani',
       'Sachin Baby', 'Salman Butt', 'Sameer Rizvi', 'Sandeep Sharma',
       'Sanvir Singh', 'Saurav Chauhan', 'Sediqullah Atal',
       'Shahbaz Ahmed', 'Shahid Afridi', 'Shakib Al Hasan',
       'Shashank Singh', 'Shivam Mavi', 'Shivam Sharma', 'Shivam Singh',
       'Shoaib Ahmed', 'Shoaib Akhtar', 'Shoaib Malik', 'Shubman Gill',
       'Sikandar Raza', 'Simarjeet Singh', 'Sohail Tanvir', 'Sumit Kumar',
       'Sunny Gupta', 'Sunny Singh', 'Suryansh Shedge', 'Suyash Sharma',
       'Swapnil Singh', 'T Banton', 'T Henderson', 'T Kohler-Cadmore',
       'T Kohli', 'T Natarajan', 'T Shamsi', 'T Stubbs', 'T Taibu',
       'T Thushara', 'TA Boult', 'TD Paine', 'TG Southee', 'TH David',
       'TK Curran', 'TL Seifert', 'TL Suman', 'TM Dilshan', 'TM Head',
       'TM Srivastava', 'TP Sudhindra', 'TR Birt', 'TS Mills',
       'TU Deshpande', 'Tanush Kotian', 'Tejas Baroka', 'Tilak Varma',
       'U Kaul', 'UA Birla', 'UBT Chand', 'UT Khawaja', 'UT Yadav',
       'Umar Gul', 'Umran Malik', 'Urvil Patel', 'V Kaverappa', 'V Kohli',
       'V Nigam', 'V Pratap Singh', 'V Puthur', 'V Sehwag', 'V Shankar',
       'V Suryavanshi', 'V Viyaskanth', 'VG Arora', 'VH Zol', 'VR Aaron',
       'VR Iyer', 'VRV Singh', 'VS Malik', 'VS Yeligati', 'VVS Laxman',
       'VY Mahesh', 'Vijaykumar Vyshak', 'Virat Singh', 'Vishnu Vinod',
       'Vivrant Sharma', 'W Jaffer', "W O'Rourke", 'WA Mota',
       'WD Parnell', 'WG Jacks', 'WP Saha', 'WPUJC Vaas',
       'Washington Sundar', 'X Thalaivan Sargunam', 'XC Bartlett',
       'Y Gnaneswara Rao', 'Y Nagar', 'Y Prithvi Raj', 'Y Venugopal Rao',
       'YA Abdulla', 'YBK Jaiswal', 'YK Pathan', 'YS Chahal', 'YV Dhull',
       'YV Takawale', 'Yash Dayal', 'Yash Thakur', 'Yashpal Singh',
       'Younis Khan', 'Yudhvir Singh', 'Yuvraj Singh', 'Z Khan',
       'Zeeshan Ansari'], dtype=object)

In [16]:
normalized_all_mapped = [normalize_name(p) for p in all_mapped]
normalized_all_mapped

['ms dhoni',
 'ravindra jadeja',
 'ruturaj gaikwad',
 'deepak chahar',
 'moeen ali',
 'shivam dube',
 'matheesha pathirana',
 'ajinkya rahane',
 'daryl mitchell',
 'mitchell santner',
 'tushar deshpande',
 'rohit sharma',
 'ishan kishan',
 'suryakumar yadav',
 'hardik pandya',
 'tim david',
 'jasprit bumrah',
 'piyush chawla',
 'tilak varma',
 'gerald coetzee',
 'romario shepherd',
 'nehal wadhera']

In [17]:
unique_venue_list_from_df = historical_data['venue'].unique()
unique_venues = list(unique_venue_list_from_df)
print(unique_venues)
def map_venue_name(name):
    
    match = get_close_matches(name, unique_venues, n=1, cutoff=0.5)
    
    if match:
        return match[0]
    else:
        return None
print(historical_data['venue'].value_counts())

['Subrata Roy Sahara Stadium', 'Wankhede Stadium', 'Barabati Stadium', 'MA Chidambaram Stadium', 'M Chinnaswamy Stadium', 'Rajiv Gandhi International Stadium', 'Arun Jaitley Stadium', 'Eden Gardens', 'Maharashtra Cricket Association Stadium', 'Sawai Mansingh Stadium', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Punjab Cricket Association IS Bindra Stadium', 'Brabourne Stadium', 'Dr DY Patil Sports Academy', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'Narendra Modi Stadium', 'Himachal Pradesh Cricket Association Stadium', 'Newlands', "St George's Park", 'Kingsmead', 'New Wanderers Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha', 'Buffalo Park', 'OUTsurance Oval', 'Nehru Stadium', 'Sheikh Zayed Stadium', 'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium', 'Shaheed Veer Narayan Singh International Stadium', 'Saurashtra Cricket Association Stadium', 'Green Park', 'JSCA International Stadium Complex', 'Barsapara Cricket Stadium', 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'De Beers Diamond Oval', 'Holkar Cricket Stadium']
venue
Wankhede Stadium                                                      2719
Eden Gardens                                                          2125
M Chinnaswamy Stadium                                                 2116
Arun Jaitley Stadium                                                  2099
MA Chidambaram Stadium                                                1991
Rajiv Gandhi International Stadium                                    1772
Sawai Mansingh Stadium                                                1347
Punjab Cricket Association IS Bindra Stadium                          1297
Narendra Modi Stadium                                                 1002
Dubai International Cricket Stadium                                    988
Sheikh Zayed Stadium                                                   788
Dr DY Patil Sports Academy                                             786
Maharashtra Cricket Association Stadium                                746
Sharjah Cricket Stadium                                                594
Brabourne Stadium                                                      567
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium           501
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    374
Subrata Roy Sahara Stadium                                             336
Kingsmead                                                              317
Himachal Pradesh Cricket Association Stadium                           309
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     260
SuperSport Park                                                        249
Saurashtra Cricket Association Stadium                                 203
Holkar Cricket Stadium                                                 188
New Wanderers Stadium                                                  184
Newlands                                                               164
Barabati Stadium                                                       149
JSCA International Stadium Complex                                     148
St George's Park                                                       144
Shaheed Veer Narayan Singh International Stadium                       126
Barsapara Cricket Stadium                                              115
Nehru Stadium                                                          107
Green Park                                                              83
Vidarbha Cricket Association Stadium, Jamtha                            65
De Beers Diamond Oval                                                   62
Buffalo Park                                                            61
OUTsurance Oval                                                         43
Name: count, dtype: int64

In [18]:
from difflib import get_close_matches
mapped_venues = map_venue_name(venue)
mapped_venues

'Wankhede Stadium'

In [21]:
players_df = data[
    data['player_key'].isin(normalized_all_mapped)
].copy()
players_df

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,player_key
7684,980905,Ishan Kishan,13.0,Punjab Cricket Association IS Bindra Stadium,2016,1,24.000000,81.785714,0.8,27.642857,56.333333,1.016947,1.0,0.0,36.168740,0.807327,-5.200000,2.0,0.727273,1,1,27.280000,1536.773333,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,True,False,ishan kishan
7685,980945,Ishan Kishan,2.0,Arun Jaitley Stadium,2016,2,35.672040,80.762144,0.0,44.444444,19.500000,1.031603,1.0,0.0,0.000000,0.000000,0.000000,2.0,0.000000,1,0,35.672040,695.604776,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,ishan kishan
7686,980949,Ishan Kishan,-2.0,Maharashtra Cricket Association Stadium,2016,3,35.672040,80.762144,0.0,20.000000,17.000000,0.992518,1.0,-0.0,0.000000,0.000000,0.000000,2.0,0.000000,1,1,35.672040,606.424677,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,ishan kishan
7687,980955,Ishan Kishan,38.0,Saurashtra Cricket Association Stadium,2016,4,4.333333,80.762144,0.0,27.642857,44.750000,1.048043,1.0,0.0,7.767453,0.000000,0.000000,2.0,0.444444,1,1,16.868816,754.879512,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,True,False,False,True,False,ishan kishan
7688,980961,Ishan Kishan,2.0,Saurashtra Cricket Association Stadium,2016,5,12.666667,80.762144,0.0,44.444444,44.750000,1.048043,1.0,0.0,17.988422,0.000000,0.000000,2.0,0.000000,1,0,21.868816,978.629512,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,ishan kishan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23066,1473493,Tilak Varma,7.0,Wankhede Stadium,2025,47,18.666667,143.084148,0.0,35.857143,33.947368,1.035196,1.0,0.0,25.954875,1.814688,-28.433333,5.0,0.000000,0,0,29.290000,994.318421,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,tilak varma
23067,1473501,Tilak Varma,30.0,Wankhede Stadium,2025,48,10.666667,124.463458,0.0,48.857143,33.947368,1.035196,1.0,0.0,28.631956,1.477370,-31.633333,5.0,0.370370,0,0,19.510000,662.313158,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,tilak varma
23068,1473506,Tilak Varma,1.0,Sawai Mansingh Stadium,2025,49,17.333333,108.705882,0.0,36.333333,43.500000,0.988582,1.0,0.0,28.054708,1.397270,-21.866667,5.0,0.000000,0,0,19.900000,865.650000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,tilak varma
23069,1473509,Tilak Varma,45.0,Maharaja Yadavindra Singh International Cricke...,2025,50,12.666667,89.000000,0.0,35.857143,51.500000,1.025162,1.0,0.0,30.214787,1.138515,-21.733333,5.0,0.720000,0,1,14.820000,763.230000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,tilak varma
23070,1473510,Tilak Varma,58.0,Narendra Modi Stadium,2025,51,25.333333,114.454545,0.0,36.333333,45.200000,1.079940,1.0,0.0,29.533597,1.127529,-7.966667,5.0,0.454545,0,0,24.410000,1103.332000,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,tilak varma

In [22]:

players_df['player'].unique()

array(['Ishan Kishan', 'MS Dhoni', 'Tilak Varma'], dtype=object)