In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/ready_for_training.csv")

In [3]:
pd.set_option("display.max_columns",None)

In [4]:
data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,player_role_wicketkeeper,match_month,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,stage_Elimination Final,stage_Eliminator,stage_Final,stage_Qualifier 1,stage_Qualifier 2,stage_Semi Final,stage_Unknown,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler
0,548341,0,58.0,53,2012,1,35.672040,35.67204,35.67204,80.762144,0.0,58.00,39.250000,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,7.0,0,4,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True
1,548346,0,41.0,56,2012,2,35.672040,35.67204,35.67204,80.762144,0.0,41.00,30.000000,1.010270,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,8.0,0,4,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False
2,548348,0,23.0,2,2012,3,35.672040,35.67204,35.67204,80.762144,0.0,23.00,39.250000,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,7.0,0,5,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True
3,548352,0,28.0,27,2012,4,40.666667,35.67204,35.67204,80.762144,0.0,45.00,47.333333,0.988070,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,6.0,0,5,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True
4,548356,0,33.0,23,2012,5,30.666667,35.67204,35.67204,80.762144,0.0,31.75,38.714286,0.964953,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,7.0,0,5,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,766,25.0,44,2025,6,3.333333,25.60000,35.67204,0.000000,0.8,6.75,18.500000,1.134422,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,11.0,0,4,0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
25121,1473480,766,0.0,28,2025,7,11.666667,13.60000,35.67204,0.000000,0.4,0.00,0.000000,1.003589,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,11.0,0,4,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False
25122,1473488,766,23.0,33,2025,8,12.333333,7.00000,35.67204,0.000000,0.2,23.00,11.500000,1.116228,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,11.0,0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
25123,1473492,766,4.0,44,2025,9,16.000000,11.60000,35.67204,0.000000,0.4,6.75,44.500000,1.134422,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,11.0,0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
25124,1473499,766,-2.0,4,2025,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.00,-2.000000,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,11.0,0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,True

In [5]:
data['recent_form'] = (data['last3_avg_points']*0.6 + data['last5_avg_points']*0.3 + data['last10_avg_points']*0.1)

In [6]:
data['venue_form'] = data['venue_avg_points'] * data['recent_form']

In [7]:
data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,player_role_wicketkeeper,match_month,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,stage_Elimination Final,stage_Eliminator,stage_Final,stage_Qualifier 1,stage_Qualifier 2,stage_Semi Final,stage_Unknown,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,recent_form,venue_form
0,548341,0,58.0,53,2012,1,35.672040,35.67204,35.67204,80.762144,0.0,58.00,39.250000,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,7.0,0,4,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,35.672040,2068.978308
1,548346,0,41.0,56,2012,2,35.672040,35.67204,35.67204,80.762144,0.0,41.00,30.000000,1.010270,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,8.0,0,4,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,35.672040,1462.553632
2,548348,0,23.0,2,2012,3,35.672040,35.67204,35.67204,80.762144,0.0,23.00,39.250000,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,7.0,0,5,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,35.672040,820.456915
3,548352,0,28.0,27,2012,4,40.666667,35.67204,35.67204,80.762144,0.0,45.00,47.333333,0.988070,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,6.0,0,5,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,38.668816,1740.096716
4,548356,0,33.0,23,2012,5,30.666667,35.67204,35.67204,80.762144,0.0,31.75,38.714286,0.964953,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,7.0,0,5,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,True,32.668816,1037.234905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,766,25.0,44,2025,6,3.333333,25.60000,35.67204,0.000000,0.8,6.75,18.500000,1.134422,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,11.0,0,4,0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,13.247204,89.418627
25121,1473480,766,0.0,28,2025,7,11.666667,13.60000,35.67204,0.000000,0.4,0.00,0.000000,1.003589,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,11.0,0,4,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,14.647204,0.000000
25122,1473488,766,23.0,33,2025,8,12.333333,7.00000,35.67204,0.000000,0.2,23.00,11.500000,1.116228,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,11.0,0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,13.067204,300.545692
25123,1473492,766,4.0,44,2025,9,16.000000,11.60000,35.67204,0.000000,0.4,6.75,44.500000,1.134422,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,11.0,0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,16.647204,112.368627
25124,1473499,766,-2.0,4,2025,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.00,-2.000000,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,11.0,0,5,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,True,12.807204,-25.614408

In [8]:
colsToDrop =  ['last5_avg_points',
              'last10_avg_points',
              'bat_pos_per_match',
              'match_month',
              'stage_Elimination Final',
              'stage_Eliminator',
              'stage_Final',
              'stage_Qualifier 1',
              'stage_Qualifier 2',
              'stage_Semi Final',
              'stage_Unknown']
data = data.drop(columns = colsToDrop)

In [9]:
data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,recent_form,venue_form
0,548341,0,58.0,53,2012,1,35.672040,80.762144,0.0,58.00,39.250000,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,35.672040,2068.978308
1,548346,0,41.0,56,2012,2,35.672040,80.762144,0.0,41.00,30.000000,1.010270,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,35.672040,1462.553632
2,548348,0,23.0,2,2012,3,35.672040,80.762144,0.0,23.00,39.250000,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,35.672040,820.456915
3,548352,0,28.0,27,2012,4,40.666667,80.762144,0.0,45.00,47.333333,0.988070,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,38.668816,1740.096716
4,548356,0,33.0,23,2012,5,30.666667,80.762144,0.0,31.75,38.714286,0.964953,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,False,True,32.668816,1037.234905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,766,25.0,44,2025,6,3.333333,0.000000,0.8,6.75,18.500000,1.134422,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,13.247204,89.418627
25121,1473480,766,0.0,28,2025,7,11.666667,0.000000,0.4,0.00,0.000000,1.003589,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,14.647204,0.000000
25122,1473488,766,23.0,33,2025,8,12.333333,0.000000,0.2,23.00,11.500000,1.116228,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,13.067204,300.545692
25123,1473492,766,4.0,44,2025,9,16.000000,0.000000,0.4,6.75,44.500000,1.134422,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,16.647204,112.368627
25124,1473499,766,-2.0,4,2025,10,9.000000,0.000000,0.4,-2.00,-2.000000,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,True,12.807204,-25.614408

In [10]:
data['season'] = data['season'].str[:4].astype(int)
data['season'].unique()

array([2012, 2013, 2015, 2016, 2022, 2023, 2024, 2025, 2007, 2009, 2017,
       2018, 2011, 2014, 2019, 2020, 2021])

In [11]:
train = data[data['season'] <= 2022].copy()
test  = data[data['season'] > 2022].copy()
X_train = train.drop(columns=['fantasy_points','player','venue','season','player_role_batsman','player_role_bowler','match_id','player_match_number'])
y_train = train['fantasy_points']

X_test = test.drop(columns=['fantasy_points','player','venue','season','player_role_batsman','player_role_bowler','match_id','player_match_number'])
y_test = test['fantasy_points']

print(X_test.shape)
print(X_train.shape)
print(test.shape)
print(train.shape)

(4995, 49)
(20130, 49)
(4995, 57)
(20130, 57)

In [12]:
# from lightgbm import LGBMRegressor
# from sklearn.model_selection import GridSearchCV

# lgbm = LGBMRegressor(
#     objective="regression",
#     n_estimators=800,
#     random_state=42,
#     reg_alpha=0.1,
#     reg_lambda=1
# )

# param_grid = {

#     "num_leaves": [100,140],

#     "max_depth": [7,9],

#     "learning_rate": [0.018,0.022],

#     "subsample": [0.85, 0.9],

#     "colsample_bytree": [0.55, 0.6],

#     "min_child_samples": [5, 8]
# }

# grid = GridSearchCV(
#     estimator=lgbm,
#     param_grid=param_grid,
#     scoring="neg_mean_absolute_error",
#     cv=2,
#     verbose=2,
#     n_jobs=-1
# )

# grid.fit(X_train, y_train)

# print("Best Params:", grid.best_params_)
# print("Best MAE:", -grid.best_score_)

In [33]:
from lightgbm import LGBMRegressor
best_params = {'subsample': 0.9, 'num_leaves': 127, 'min_child_samples': 5, 'max_depth': 10, 'learning_rate': 0.02, 'colsample_bytree': 0.6}

final_model = LGBMRegressor(
    n_estimators=600,
    random_state=42,
    reg_alpha = 0.1,
    reg_lambda = 1,
    **best_params
)

final_model.fit(
    X_train,
    y_train,
)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000929 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3148
[LightGBM] [Info] Number of data points in the train set: 20130, number of used features: 49
[LightGBM] [Info] Start training from score 35.483756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMRegressor(colsample_bytree=0.6, learning_rate=0.02, max_depth=10,
              min_child_samples=5, n_estimators=600, num_leaves=127,
              random_state=42, reg_alpha=0.1, reg_lambda=1, subsample=0.9)

In [34]:
y_pred = final_model.predict(X_test)

In [35]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test, y_pred))

13.232406272019233

In [36]:
test['predictions'] = y_pred

In [37]:
import joblib
le_player = joblib.load("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/encoders/player_encoder.pkl")
le_venue = joblib.load("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/encoders/venue_encoder.pkl")
test['player'] = le_player.inverse_transform(test['player'])
test['venue'] = le_venue.inverse_transform(test['venue'])
test

TypeError: '<' not supported between instances of 'str' and 'int'

In [18]:
test.columns

Index(['match_id', 'player', 'fantasy_points', 'venue', 'season',
       'player_match_number', 'last3_avg_points', 'rolling_strike_rate',
       'rolling_wickets', 'venue_avg_points', 'opponent_avg_points',
       'venue_run_factor', 'batting_contribution_ratio',
       'bowling_contribution_ratio', 'last10_std_points',
       'player_consistency_index', 'form_momentum', 'bat_pos',
       'boundary_percentage', 'player_role_wicketkeeper', 'team_won_toss',
       'team_Deccan Chargers', 'team_Delhi Capitals', 'team_Gujarat Lions',
       'team_Gujarat Titans', 'team_Kochi Tuskers Kerala',
       'team_Kolkata Knight Riders', 'team_Lucknow Super Giants',
       'team_Mumbai Indians', 'team_Pune Warriors', 'team_Punjab Kings',
       'team_Rajasthan Royals', 'team_Rising Pune Supergiants',
       'team_Royal Challengers Bengaluru', 'team_Sunrisers Hyderabad',
       'opponent_Deccan Chargers', 'opponent_Delhi Capitals',
       'opponent_Gujarat Lions', 'opponent_Gujarat Titans',
       'opponent_Kochi Tuskers Kerala', 'opponent_Kolkata Knight Riders',
       'opponent_Lucknow Super Giants', 'opponent_Mumbai Indians',
       'opponent_Pune Warriors', 'opponent_Punjab Kings',
       'opponent_Rajasthan Royals', 'opponent_Rising Pune Supergiants',
       'opponent_Royal Challengers Bengaluru', 'opponent_Sunrisers Hyderabad',
       'toss_decision_field', 'pitch_type_batting_friendly',
       'pitch_type_pace_friendly', 'pitch_type_spin_friendly',
       'player_role_batsman', 'player_role_bowler', 'recent_form',
       'venue_form', 'predictions'],
      dtype='object')

In [19]:
best_team_actual = (
    test.sort_values(['match_id','fantasy_points'], ascending=[True, False])
        .groupby('match_id')
        .head(11)
)
best_team_actual

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,recent_form,venue_form,predictions
17412,1359475,RD Gaikwad,136.0,"Narendra Modi Stadium, Ahmedabad",2023,37,25.666667,101.605479,0.0,59.000000,70.857143,1.116228,1.0,0.0,44.810713,1.071172,-22.333333,1.0,0.760870,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,31.300000,1846.700000,80.634754
22337,1359475,Shubman Gill,97.0,"Narendra Modi Stadium, Ahmedabad",2023,71,35.000000,106.154322,0.0,64.280000,40.250000,1.116228,1.0,0.0,27.011109,1.392020,-2.600000,2.0,0.666667,0,1,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,37.000000,2378.360000,44.499494
18253,1359475,RS Hangargekar,79.0,"Narendra Modi Stadium, Ahmedabad",2023,1,35.672040,80.762144,0.0,79.000000,79.000000,1.116228,0.0,1.0,0.000000,0.000000,0.000000,11.0,0.000000,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,35.672040,2818.091144,100.529272
18614,1359475,Rashid Khan,73.0,"Narendra Modi Stadium, Ahmedabad",2023,93,37.000000,63.333333,1.6,37.521739,43.944444,1.116228,0.2,0.8,39.242975,1.291951,-13.700000,8.0,1.000000,0,1,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,43.470000,1631.070000,34.373666
13812,1359475,Mohammed Shami,58.0,"Narendra Modi Stadium, Ahmedabad",2023,94,22.000000,0.000000,1.0,43.642857,30.000000,1.116228,0.0,1.0,29.628065,1.296068,-16.400000,9.0,0.000000,0,1,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,27.420000,1196.687143,37.894251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22576,1485779,T Stubbs,60.0,"Sawai Mansingh Stadium, Jaipur",2025,31,27.333333,119.222222,0.0,65.000000,32.500000,1.124459,1.0,0.0,22.232109,1.547312,-7.066667,6.0,0.444444,1,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,27.880000,1812.200000,45.907055
23558,1485779,V Nigam,58.0,"Sawai Mansingh Stadium, Jaipur",2025,14,20.666667,141.176471,0.4,58.000000,58.000000,1.124459,0.0,1.0,41.108123,0.805194,-12.433333,7.0,0.000000,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,27.590000,1600.220000,56.755720
10239,1485779,KL Rahul,51.0,"Sawai Mansingh Stadium, Jaipur",2025,135,60.000000,134.439560,0.0,66.666667,42.600000,1.124459,1.0,0.0,54.970699,1.073299,1.000000,1.0,0.857143,1,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,56.060000,3737.333333,53.988474
10753,1485779,Kuldeep Yadav,50.0,"Sawai Mansingh Stadium, Jaipur",2025,98,10.000000,37.500000,0.2,40.500000,37.714286,1.124459,0.0,1.0,25.299319,0.810298,-10.500000,9.0,0.000000,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,9.910000,401.355000,48.701057
8984,1485779,JP Inglis,49.0,"Sawai Mansingh Stadium, Jaipur",2025,7,28.333333,150.112045,0.0,79.500000,49.000000,1.124459,1.0,0.0,14.746751,0.000000,0.000000,3.0,0.750000,1,0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,29.927204,2379.212716,97.301570

In [20]:
best_team_predicted = (
    test.sort_values(['match_id','predictions'], ascending=[True, False])
        .groupby('match_id')
        .head(11)
)

In [21]:
best_team_predicted

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,recent_form,venue_form,predictions
18253,1359475,RS Hangargekar,79.0,"Narendra Modi Stadium, Ahmedabad",2023,1,35.672040,80.762144,0.0,79.000000,79.000000,1.116228,0.000000,1.000000,0.000000,0.000000,0.000000,11.0,0.000000,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,35.672040,2818.091144,100.529272
3100,1359475,B Sai Sudharsan,27.0,"Narendra Modi Stadium, Ahmedabad",2023,6,41.000000,128.334364,0.0,70.210526,80.000000,1.116228,1.000000,0.000000,26.975915,0.000000,0.000000,3.0,0.545455,0,1,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,39.507204,2773.821585,88.879862
17412,1359475,RD Gaikwad,136.0,"Narendra Modi Stadium, Ahmedabad",2023,37,25.666667,101.605479,0.0,59.000000,70.857143,1.116228,1.000000,0.000000,44.810713,1.071172,-22.333333,1.0,0.760870,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,31.300000,1846.700000,80.634754
17153,1359475,RA Jadeja,34.0,"Narendra Modi Stadium, Ahmedabad",2023,204,18.000000,102.416667,0.2,46.250000,50.857143,1.116228,0.029412,0.970588,26.597619,1.282070,-16.100000,6.0,0.000000,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,21.530000,995.762500,56.504180
22337,1359475,Shubman Gill,97.0,"Narendra Modi Stadium, Ahmedabad",2023,71,35.000000,106.154322,0.0,64.280000,40.250000,1.116228,1.000000,0.000000,27.011109,1.392020,-2.600000,2.0,0.666667,0,1,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,37.000000,2378.360000,44.499494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10092,1485779,KK Nair,61.0,"Sawai Mansingh Stadium, Jaipur",2025,76,16.000000,110.854701,0.0,61.000000,61.000000,1.124459,1.000000,0.000000,38.352169,0.730076,-12.000000,3.0,0.727273,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,19.960000,1217.560000,67.618642
6092,1485779,F du Plessis,39.0,"Sawai Mansingh Stadium, Jaipur",2025,147,3.666667,80.424675,0.0,55.000000,58.625000,1.124459,1.000000,0.000000,37.196923,1.008148,-33.833333,2.0,0.608696,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,13.030000,716.650000,64.346953
23558,1485779,V Nigam,58.0,"Sawai Mansingh Stadium, Jaipur",2025,14,20.666667,141.176471,0.4,58.000000,58.000000,1.124459,0.000000,1.000000,41.108123,0.805194,-12.433333,7.0,0.000000,0,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,27.590000,1600.220000,56.755720
10239,1485779,KL Rahul,51.0,"Sawai Mansingh Stadium, Jaipur",2025,135,60.000000,134.439560,0.0,66.666667,42.600000,1.124459,1.000000,0.000000,54.970699,1.073299,1.000000,1.0,0.857143,1,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,56.060000,3737.333333,53.988474
15925,1485779,Priyansh Arya,15.0,"Sawai Mansingh Stadium, Jaipur",2025,14,37.333333,141.985994,0.0,40.666667,58.000000,1.124459,1.000000,0.000000,47.234168,1.160177,-17.466667,1.0,0.666667,0,0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,42.940000,1746.226667,52.690530

In [22]:
print("Actual:")
print(best_team_actual[best_team_actual['match_id'] == 1359475]['player'])
print("Predicted-:")
print(best_team_predicted[best_team_predicted['match_id'] == 1359475]['player'])

Actual:
17412        RD Gaikwad
22337      Shubman Gill
18253    RS Hangargekar
18614       Rashid Khan
13812    Mohammed Shami
24187           WP Saha
1976          AS Joseph
23725         V Shankar
17153         RA Jadeja
7850           J Little
12795            MM Ali
Name: player, dtype: object
Predicted-:
18253     RS Hangargekar
3100     B Sai Sudharsan
17412         RD Gaikwad
17153          RA Jadeja
22337       Shubman Gill
23725          V Shankar
13812     Mohammed Shami
12795             MM Ali
18614        Rashid Khan
22979       TU Deshpande
19133             S Dube
Name: player, dtype: object

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 13.293560394809056
RMSE: 19.710986312655788
R2: 0.6677491311247564

In [24]:
from scipy.stats import spearmanr

corr, _ = spearmanr(y_test, y_pred)
print("Spearman Rank Correlation:", corr)

Spearman Rank Correlation: 0.8442332832963065

In [25]:
results = X_test.copy()

results['actual_points'] = y_test
results['predicted_points'] = y_pred
results['player'] = test['player']
results['match_id'] = test['match_id']

In [26]:
results

,last3_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,recent_form,venue_form,actual_points,predicted_points,player,match_id
39,25.666667,76.666667,0.4,28.277778,31.333333,1.040207,1.0,0.0,10.926014,2.159983,2.066667,6.0,0.888889,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,26.040000,736.353333,23.0,27.755338,A Badoni,1359477
40,21.000000,102.640693,0.2,16.000000,39.500000,1.003589,1.0,0.0,10.926014,2.159983,-2.600000,6.0,0.000000,0,1,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,22.160000,354.560000,23.0,9.099830,A Badoni,1359480
41,23.000000,108.196248,0.2,18.000000,17.000000,1.148566,1.0,0.0,10.298328,2.184821,0.500000,6.0,0.533333,0,1,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,23.430000,421.740000,38.0,18.520098,A Badoni,1359489
42,28.000000,116.529582,0.2,28.277778,43.000000,1.040207,1.0,0.0,11.370527,2.128309,3.800000,6.0,0.000000,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,26.660000,753.885556,5.0,11.662662,A Badoni,1359495
43,22.000000,118.650794,0.2,23.000000,21.000000,1.124459,1.0,0.0,11.370527,2.128309,-2.200000,6.0,0.000000,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,22.340000,513.820000,1.0,8.178332,A Badoni,1359500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,3.333333,0.000000,0.8,6.750000,18.500000,1.134422,0.0,1.0,36.004166,0.000000,0.000000,11.0,0.000000,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,13.247204,89.418627,25.0,9.054985,Zeeshan Ansari,1473478
25121,11.666667,0.000000,0.4,0.000000,0.000000,1.003589,0.0,0.0,32.204037,0.000000,0.000000,11.0,0.000000,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,14.647204,0.000000,0.0,-0.517806,Zeeshan Ansari,1473480
25122,12.333333,0.000000,0.2,23.000000,11.500000,1.116228,0.0,1.0,30.937725,0.000000,0.000000,11.0,0.000000,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,13.067204,300.545692,23.0,19.524726,Zeeshan Ansari,1473488
25123,16.000000,0.000000,0.4,6.750000,44.500000,1.134422,-0.0,1.0,28.645618,0.000000,0.000000,11.0,0.000000,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,16.647204,112.368627,4.0,13.691991,Zeeshan Ansari,1473492
25124,9.000000,0.000000,0.4,-2.000000,-2.000000,1.040207,-0.0,1.0,27.459060,0.000000,0.000000,11.0,0.000000,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,12.807204,-25.614408,-2.0,-4.079565,Zeeshan Ansari,1473499

In [27]:
correct_counts = []

for match in results['match_id'].unique():

    match_df = results[results['match_id'] == match]

    predicted_top11 = match_df.sort_values(
        'predicted_points', ascending=False
    ).head(11)['player']

    actual_top11 = match_df.sort_values(
        'actual_points', ascending=False
    ).head(11)['player']

    overlap = len(set(predicted_top11) & set(actual_top11))

    correct_counts.append(overlap)

print("Average correct players in top 11:", sum(correct_counts)/len(correct_counts))

Average correct players in top 11: 9.141552511415526

In [28]:
data

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,venue_avg_points,opponent_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,team_won_toss,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,toss_decision_field,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_batsman,player_role_bowler,recent_form,venue_form
0,548341,0,58.0,53,2012,1,35.672040,80.762144,0.0,58.00,39.250000,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,35.672040,2068.978308
1,548346,0,41.0,56,2012,2,35.672040,80.762144,0.0,41.00,30.000000,1.010270,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,35.672040,1462.553632
2,548348,0,23.0,2,2012,3,35.672040,80.762144,0.0,23.00,39.250000,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,35.672040,820.456915
3,548352,0,28.0,27,2012,4,40.666667,80.762144,0.0,45.00,47.333333,0.988070,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,38.668816,1740.096716
4,548356,0,33.0,23,2012,5,30.666667,80.762144,0.0,31.75,38.714286,0.964953,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False,False,True,32.668816,1037.234905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,766,25.0,44,2025,6,3.333333,0.000000,0.8,6.75,18.500000,1.134422,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,13.247204,89.418627
25121,1473480,766,0.0,28,2025,7,11.666667,0.000000,0.4,0.00,0.000000,1.003589,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,14.647204,0.000000
25122,1473488,766,23.0,33,2025,8,12.333333,0.000000,0.2,23.00,11.500000,1.116228,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,13.067204,300.545692
25123,1473492,766,4.0,44,2025,9,16.000000,0.000000,0.4,6.75,44.500000,1.134422,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,16.647204,112.368627
25124,1473499,766,-2.0,4,2025,10,9.000000,0.000000,0.4,-2.00,-2.000000,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,True,12.807204,-25.614408

In [29]:
data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data.csv",index = False)