In [22]:
import numpy as np
import pandas as pd
import joblib

In [23]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/training_data_final.csv")

In [24]:
pd.set_option("display.max_columns",None)

In [25]:
data = data.iloc[:,1:]

In [26]:
data

,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,player_role_wicketkeeper,recent_form,venue_form,team_Deccan Chargers,team_Delhi Capitals,team_Gujarat Lions,team_Gujarat Titans,team_Kochi Tuskers Kerala,team_Kolkata Knight Riders,team_Lucknow Super Giants,team_Mumbai Indians,team_Pune Warriors,team_Punjab Kings,team_Rajasthan Royals,team_Rising Pune Supergiants,team_Royal Challengers Bengaluru,team_Sunrisers Hyderabad,opponent_Deccan Chargers,opponent_Delhi Capitals,opponent_Gujarat Lions,opponent_Gujarat Titans,opponent_Kochi Tuskers Kerala,opponent_Kolkata Knight Riders,opponent_Lucknow Super Giants,opponent_Mumbai Indians,opponent_Pune Warriors,opponent_Punjab Kings,opponent_Rajasthan Royals,opponent_Rising Pune Supergiants,opponent_Royal Challengers Bengaluru,opponent_Sunrisers Hyderabad,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly
0,35.672040,80.762144,0.0,39.250000,58.00,0.879923,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,35.672040,2068.978308,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,35.672040,80.762144,0.0,30.000000,41.00,1.035196,0.292683,0.707317,0.000000,0.0,0.0,7.0,0.6,0,35.672040,1462.553632,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False
2,35.672040,80.762144,0.0,39.250000,23.00,1.027630,0.000000,1.000000,0.000000,0.0,0.0,7.0,0.0,0,35.672040,820.456915,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,40.666667,80.762144,0.0,47.333333,45.00,0.984847,0.107143,0.892857,17.502381,0.0,0.0,7.0,0.0,0,38.668816,1740.096716,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,30.666667,80.762144,0.0,38.714286,31.75,1.016059,0.000000,1.000000,15.631165,0.0,0.0,7.0,0.0,0,32.668816,1037.234905,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,3.333333,0.000000,0.8,18.500000,6.75,0.994802,0.000000,1.000000,36.004166,0.0,0.0,11.0,0.0,0,13.247204,89.418627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
25121,11.666667,0.000000,0.4,0.000000,0.00,0.984847,0.000000,0.000000,32.204037,0.0,0.0,11.0,0.0,0,14.647204,0.000000,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25122,12.333333,0.000000,0.2,11.500000,23.00,1.079940,0.000000,1.000000,30.937725,0.0,0.0,11.0,0.0,0,13.067204,300.545692,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
25123,16.000000,0.000000,0.4,44.500000,6.75,0.994802,-0.000000,1.000000,28.645618,0.0,0.0,11.0,0.0,0,16.647204,112.368627,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25124,9.000000,0.000000,0.4,-2.000000,-2.00,1.040207,-0.000000,1.000000,27.459060,0.0,0.0,11.0,0.0,0,12.807204,-25.614408,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False

In [27]:
joblib.dump(data.columns.tolist(), "/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/models/model_cols.pkl")

['/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/models/model_cols.pkl']

In [28]:
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/database_csv.csv")

In [30]:
data[data['player_role_wicketkeeper'] == 1]['player'].unique()

array(['AB de Villiers', 'Gurkeerat Singh', 'Ishan Kishan', 'KL Rahul',
       'Kamran Akmal', 'MS Dhoni', 'Vishnu Vinod'], dtype=object)

In [31]:
data

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,maiden_points,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,player_role_wicketkeeper
0,548341,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,0.0,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0
1,548346,Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,0.0,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,35.672040,35.67204,35.67204,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,0
2,548348,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0
3,548352,Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,0.0,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,35.67204,35.67204,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,0
4,548356,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,0.0,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,2012-05-06,5,30.666667,35.67204,35.67204,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,0.0,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.60000,35.67204,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,11.0,0
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.60000,35.67204,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,11.0,0
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.00000,35.67204,0.000000,0.2,11.500000,balanced,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,11.0,0
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,0.0,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.60000,35.67204,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,11.0,0
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,0.0,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.000000,balanced,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,11.0,0

In [42]:
raw_data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/raw/IPL.csv")

/var/folders/9x/3x7xy3b937b7s21dnh9vzpp00000gn/T/ipykernel_5370/2677229689.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/raw/IPL.csv")

In [33]:
wk_list = raw_data.loc[raw_data['wicket_kind']=='stumped','fielders'].unique()

In [34]:
wk_list =

array(['MV Boucher', 'Kamran Akmal', 'WP Saha', 'YV Takawale',
       'AC Gilchrist', 'KD Karthik', 'SP Goswami', 'RV Uthappa',
       'MS Dhoni', 'PR Shah', 'M Rawat', 'NV Ojha', 'KC Sangakkara',
       'AP Tare', 'PA Patel', 'AT Rayudu', 'AB de Villiers', 'DJ Jacobs',
       'MS Bisla', 'DH Yagnik', 'KH Devdhar', 'N Saini', 'BB McCullum',
       'KB Arun Karthik', 'KM Jadhav', 'Q de Kock', 'Gurkeerat Singh',
       'CM Gautam', 'SV Samson', 'KL Rahul', 'RR Pant', 'Vishnu Vinod',
       'Ishan Kishan', 'JC Buttler', 'H Klaasen', 'JM Bairstow',
       'KS Bharat', 'SP Jackson', 'SW Billings', 'N Pooran', 'JM Sharma',
       'MS Wade', 'P Simran Singh', 'RD Rickelton', 'JP Inglis',
       'T Stubbs'], dtype=object)

In [35]:
data["player_role_wicketkeeper"] = data["player"].isin(wk_list).astype(int)

In [38]:
data['player'].unique()

array(['Ashish Reddy', 'Ayush Badoni', 'Ajit Chandila', 'Aakash Chopra',
       'Aniket Choudhary', 'Akila Dananjaya', 'Andrew Flintoff',
       'Anshul Kamboj', 'Anil Kumble', 'Abhinav Manohar', 'Ayush Mhatre',
       'Amit Mishra', 'Abhimanyu Mithun', 'Abhinav Mukund',
       'Ashish Nehra', 'André Nel', 'Anrich Nortje',
       'Angkrish Raghuvanshi', 'Anureet Singh', 'Andrew Symonds',
       'Anshuman Tomar', 'Amit Uniyal', 'Adam Zampa', 'Akshath Bilakhia',
       'Ankeet Chavan', 'Abhishek Jhunjhunwala', 'Abrar Kazi',
       'Arshin Kulkarni', 'Ashley Noffke', 'Ajit Agarkar',
       'Adrian Barath', 'Ashoke Dinda', 'Andrew McDonald',
       'AB de Villiers', 'Aiden Blizzard', 'Adam Gilchrist',
       'Alfonso Thomas', 'Adam Voges', 'Alex Hales',
       'Dimitri Mascarenhas', 'Angelo Mathews', 'Akshdeep Nath',
       'Andre Russell', 'Adam Milne', 'Ali Murtaza', 'Amit Paunikar',
       'Aaron Finch', 'Akeal Hosein', 'Ashton Turner', 'Andrew Tye',
       'Aiden Markram', 'Ashok Menaria', 'Abhishek Nayar',
       'Ajinkya Rahane', 'Aavishkar Salvi', 'Abu Nechim', 'Arindam Ghosh',
       'Aditya Dole', 'Anustup Majumdar', 'Aditya Tare', 'Ankit Bawne',
       'Axar Patel', 'Alzarri Joseph', 'Ankit Rajpoot', 'Abhishek Raut',
       'Anukul Roy', 'Suryakumar Yadav', 'Alex Carey', 'Ambati Rayudu',
       'Adil Rashid', 'Asad Pathan', 'Abdul Basith', 'Abdul Samad',
       'Abdur Razzak', 'Abhishek Sharma', 'Abishek Porel', 'Akash Deep',
       'Akash Madhwal', 'Akash Singh', 'Aman Hakim Khan', 'Anand Rajan',
       'Aniket Verma', 'Anirudh Singh', 'Ankit Sharma', 'Ankit Soni',
       'Anmolpreet Singh', 'Anuj Rawat', 'Arjun Tendulkar', 'Arshad Khan',
       'Arshad Khan (2)', 'Arshdeep Singh', 'Ashutosh Sharma',
       'Ashwani Kumar', 'Atharva Taide', 'Avesh Khan', 'Azhar Mahmood',
       'Azmatullah Omarzai', 'Balachandra Akhil', 'Bharat Chipli',
       'Brett Geeves', 'Baba Indrajith', 'Bhuvaneshwar Kumar',
       'Ben Laughlin', 'Brett Lee', 'Sai Sudharsan', 'Billy Stanlake',
       'Bodanapu Sumanth', 'Bhargav Bhatt', 'Ben Stokes',
       'Ajantha Mendis', 'Brendon McCullum', 'Biplab Samantray',
       'Barinder Sran', 'Ben Cutting', 'Beuran Hendricks', 'Brad Haddin',
       'Brad Hodge', 'Ben Rohrer', 'Jeevan Mendis', 'Ben Dunk',
       'Barafe Sharath', 'Ben Hilfenhaus', 'Basil Thampi', 'Bipul Sharma',
       'Corbin Bosch', 'Chandrasekar Ganapathy', 'Cameron Green',
       'Chandan Madan', 'Colin Munro', 'Chetan Nanda', 'Chetan Sakariya',
       'Colin de Grandhomme', 'Colin Ingram', 'Chris Lynn',
       'Cheteshwar Pujara', 'Chris Gayle', 'Chris Morris',
       'Corey Anderson', 'Junior Dala', 'Callum Ferguson', 'Chris Green',
       'Chris Jordan', 'Clint McKay', 'Chamara Kapugedera',
       'Charl Langeveldt', 'Cameron White', 'C. M. Gautam',
       'Carlos Brathwaite', 'Chris Woakes', 'Dilhara Fernando',
       'Varun Chakravarthy', 'Dewald Brevis', 'Donovan Ferreira',
       'Duan Jansen', 'Doddapaneni Kalyankrishna', 'Devdutt Padikkal',
       'Dwaine Pretorius', 'Dinesh Salunkhe', 'David Wiese',
       'Dillon du Preez', 'David Miller', 'David Warner',
       'Doug Bracewell', 'Debabrata Das', 'Dwaraka Ravi Teja',
       'Doug Bollinger', 'Darshan Nalkande', 'Dishant Yagnik',
       'Dwayne Bravo', 'Daniel Harris', 'Deepak Hooda', 'David Hussey',
       'Davy Jacobs', 'Dawid Malan', 'Daryl Mitchell',
       'Domnic Muthuswami', 'Dominic Thornely', 'David Willey',
       'Darren Sammy', "D'Arcy Short", 'Deepak Chahar', 'Daniel Vettori',
       'Darren Bravo', 'Nuwan Zoysa', 'Devon Conway', 'Dirk Nannes',
       'Doddapaneni Vijaykumar', 'Mahela Jayawardene', 'Damien Martyn',
       'Daniel Sams', 'Dhruv Shorey', 'Dwayne Smith', 'Dhawal Kulkarni',
       'Darren Lehmann', 'Dhruv Rathi', 'Dan Christian', 'Dinesh Patil',
       'Dale Steyn', 'Dhruv Jurel', 'Evin Lewis', 'Lasith Malinga',
       'Eoin Morgan', 'Eklavya Dwivedi', 'Farhaan Behardien',
       'Faf du Plessis', 'Fabian Allen', 'Fidel Edwards', 'Faiz Fazal',
       'Fazalhaq Farooqi', 'Gerald Coetzee', 'Gautam Gambhir',
       'Brad Hogg', 'Graeme Smith', 'Hardus Viljoen', 'Glenn McGrath',
       'Glenn Phillips', 'Hanuma Vihari', 'George Garton',
       'George Bailey', 'Glenn Maxwell', 'Graham Napier',
       'Gurinder Sandhu', 'Gagandeep Singh', 'Gulbadin Naib',
       'Gurkeerat Singh', 'Gurnoor Brar', 'Halhadar Das',
       'Heinrich Klaasen', 'Himanshu Sharma', 'Harry Brook',
       'Rassie van der Dussen', 'Harry Gurney', 'Herschelle Gibbs',
       'Hardik Pandya', 'Hashim Amla', 'Hrithik Shokeen', 'Harshal Patel',
       'Harbhajan Singh', 'Harmeet Singh', 'Harpreet Brar',
       'Harpreet Singh', 'Harsh Dubey', 'Harshit Rana', 'Ishan Malhotra',
       'Ishant Sharma', 'Isuru Udana', 'Ishwar Pandey', 'Ishan Porel',
       'Irfan Pathan', 'Ishank Jaggi', 'Ish Sodhi', 'Imran Tahir',
       'Iqbal Abdulla', 'Ishan Kishan', 'Jagadeesh Arunkumar',
       'Johan Botha', 'Jake Fraser-McGurk', 'Joshua Little',
       'Jamie Overton', 'Jagadeesha Suchith', 'Jamaluddin Syed Mohammad',
       'Juan Theron', 'Jayant Yadav', 'Albie Morkel', 'Jhye Richardson',
       'Jofra Archer', 'Jos Buttler', 'Jesse Ryder', 'Jaydev Unadkat',
       'Jacob Oram', 'Jimmy Neesham', 'Joe Root', 'Jerome Taylor',
       'James Franklin', 'Jacob Bethell', 'Jacques Kallis',
       'Jasprit Bumrah', 'Jason Roy', 'Johan van der Wath', 'Joe Denly',
       'James Pattinson', 'Jonny Bairstow', 'Justin Kemp',
       'Jitesh Sharma', 'Jason Holder', 'Jason Behrendorff', 'JP Duminy',
       'James Faulkner', 'Josh Inglis', 'Javon Searles', 'Josh Hazlewood',
       'James Hopes', 'Josh Philippe', 'John Hastings', 'Jalaj S Saxena',
       'Jaskaran Singh', 'Joginder Sharma', 'Karan Goel',
       'Krishnappa Gowtham', 'Kumar Kartikeya', 'Kulwant Khejroliya',
       'Kagiso Rabada', 'Krishmar Santokie', 'Krishnakumar Upadhyay',
       'Kuldeep Yadav', 'Kyle Jamieson', 'Keshav Maharaj',
       'Kieron Pollard', 'Kemar Roach', 'Arun Karthik', 'K. C. Cariappa',
       'Kumar Sangakkara', 'Dinesh Karthik', 'Krunal Pandya',
       'Kyle Abbott', 'Khaleel Ahmed', 'Kevon Cooper', 'Karun Nair',
       'Kamlesh Nagarkoti', 'KL Rahul', 'KM Asif', 'Kedar Jadhav',
       'Keemo Paul', 'Nuwan Kulasekara', 'Kotarangada Appanna',
       'Kevin Pietersen', 'Kyle Mayers', 'Kuldeep Sen', 'Srikar Bharat',
       'Kunal Singh Rathore', 'Karn Sharma', 'Kane Williamson',
       'Kwena Maphaka', 'Kane Richardson', 'Kamran Akmal', 'Kamran Khan',
       'Karanveer Singh', 'Karim Janat', 'Kartik Tyagi', 'Kumar Kushagra',
       'Love Ablish', 'Lakshmipathy Balaji', 'Lungi Ngidi', 'Luke Ronchi',
       'Luke Wood', 'Lee Carseldine', 'Luke Pomersbach',
       'Lizaad Williams', 'Liam Plunkett', 'Lockie Ferguson',
       'Lukman Meriwala', 'Luke Wright', 'Lendl Simmons', 'Chamara Silva',
       'Laxmi Ratan Shukla', 'Ross Taylor', 'Liam Livingstone',
       'Lalit Yadav', 'Liton Das', 'Murugan Ashwin', 'Marco Jansen',
       'Mohammad Kaif', 'Murali Kartik', 'Michael Klinger',
       'Mithun Manhas', 'Mayank Markande', 'Morne Morkel',
       'Muttiah Muralitharan', 'Makhaya Ntini', 'Matheesha Pathirana',
       'Prasidh Krishna', 'Mahesh Rawat', 'Shahrukh Khan',
       'Manimaran Siddharth', 'Maheesh Theekshana', 'Manoj Tiwary',
       'Murali Vijay', 'Manan Vohra', 'Marchant de Lange',
       'Mayank Agarwal', 'Musavir Khote', 'Mitchell Starc', 'Mark Wood',
       'Mohnish Parmar', 'Moises Henriques', 'Manpreet Juneja',
       'Mohnish Mishra', 'Dasun Shanaka', 'Kusal Perera',
       'Michael Hussey', 'Farveez Maharoof', 'Michael Bracewell',
       'Mitchell Johnson', 'Michael Neser', 'Michael Clarke',
       'Martin Guptill', 'Matt Henry', 'Michael Lumb',
       'Mitchell McClenaghan', 'Mitchell Owen', 'Mitchell Santner',
       'Manav Suthar', 'Mahipal Lomror', 'Manish Pandey',
       'Matthew Hayden', 'Moeen Ali', 'Munaf Patel', 'Mohit Sharma',
       'Marlon Samuels', 'Morne van Wyk', 'Matthew Breetzke',
       'Marcus Stoinis', 'Mayank Yadav', 'Mitchell Marsh',
       'Manoj Bhandage', 'Manvinder Bisla', 'MS Dhoni', 'Manpreet Gony',
       'Matthew Wade', 'Mark Boucher', 'Matthew Short', 'Mandeep Singh',
       'Mashrafe Mortaza', 'Mayank Dagar', 'Misbah-ul-Haq',
       'Mohammad Ashraful', 'Mohammad Asif', 'Mohammad Hafeez',
       'Mohammad Nabi', 'Mohammed Shami', 'Mohammed Siraj',
       'Mohit Rathee', 'Mohsin Khan', 'Monu Kumar', 'Mujeeb Ur Rahman',
       'Mukesh Choudhary', 'Mukesh Kumar', 'Musheer Khan',
       'Mustafizur Rahman', 'Nandre Burger', 'Narayan Jagadeesan',
       'Nicholas Pooran', 'Nitish Rana', 'Navdeep Saini',
       'Nuwan Thushara', 'Nehal Wadhera', 'Nikhil Singh', 'Nayan Doshi',
       'Nic Maddinson', 'Nathan Rimmington', 'Niraj Patel',
       'Nathan McCullum', 'Thisara Perera', 'Nathan Coulter-Nile',
       'Nikhil Naik', 'Nathan Ellis', 'Naman Ojha', 'Naman Dhir',
       'Naveen-ul-Haq', 'Nithish Kumar Reddy', 'Noor Ahmad',
       'Oshane Thomas', 'Owais Shah', 'Obed McCoy', 'Odean Smith',
       'Palani Amarnath', 'Parvinder Awana', 'Prashant Chopra',
       'Paras Dogra', 'Praveen Dubey', 'Praveen Kumar', 'Pawan Negi',
       'Prasanth Parameswaran', 'Padmanabhan Prasanth',
       'Prayas Ray Barman', 'Pardeep Sahu', 'Prabhsimran Singh',
       'Pawan Suyal', 'Parthiv Patel', 'Akshath Reddy',
       'Bhanuka Rajapaksa', 'Paul Valthaty', 'Paul Collingwood',
       'Phil Salt', 'Prashant Solanki', 'Kamindu Mendis', 'Pat Cummins',
       'Pradeep Sangwan', 'Priyam Garg', 'Sarvesh Kumar', 'Prerak Mankad',
       'Piyush Chawla', 'Pragyan Ojha', 'Prithvi Shaw', 'Pinal Shah',
       'Peter Handscomb', 'Pravin Tambe', 'Dushmantha Chameera',
       'Venugopal Rao', 'Wiaan Mulder', 'Wanindu Hasaranga',
       'Pankaj Singh', 'Parvez Rasool', 'Prince Yadav', 'Priyansh Arya',
       'Quinton de Kock', 'Ravichandran Ashwin', 'Rajat Bhatia',
       'Ravi Bishnoi', 'Rishi Dhawan', 'Rahul Dravid', 'Ravi Goyal',
       'Ryan McLaren', 'Robin Minz', 'Ryan Ninan', 'Riyan Parag',
       'Rovman Powell', 'Ravi Rampaul', 'Rachin Ravindra',
       'Ravisrinivasan Sai Kishore', 'Sanjay Yadav', 'Rajagopal Sathish',
       'Rahul Sharma', 'Romario Shepherd', 'Rahul Shukla',
       'Rahul Tewatia', 'Vinay Kumar', 'Raj Bawa', 'Ravindra Jadeja',
       'Rahil Shaikh', 'Rahul Tripathi', 'Rahul Chahar',
       'Ruturaj Gaikwad', 'Ryan Rickelton', 'Richard Levi',
       'Roelof van der Merwe', 'Ronit More', 'Rohit Sharma',
       'Richard Gleeson', 'Ryan Harris', 'Robin Peterson', 'Rob Quiney',
       'Reece Topley', 'Ricky Bhui', 'Rinku Singh', 'Rajat Patidar',
       'Ryan ten Doeschate', 'Riley Meredith', 'R. P. Singh',
       'Raju Bhatkal', 'Ranadeb Bose', 'Rishabh Pant', 'Ramesh Powar',
       'Rohan Raje', 'Rilee Rossouw', 'Ramnaresh Sarwan', 'Ravi Bopara',
       'Rohan Gavaskar', 'Rajvardhan Hangargekar', 'Reetinder Sodhi',
       'Ricky Ponting', 'Raiphi Gomez', 'Ripal Patel', 'Robin Uthappa',
       'Ray Price', 'Rahmanullah Gurbaz', 'Ramandeep Singh',
       'Rashid Khan', 'Rasikh Salam', 'Anirudha Srikkanth',
       'Sreenath Aravind', 'Samuel Badree', 'Subramaniam Badrinath',
       'Shivnarine Chanderpaul', 'Shikhar Dhawan', 'Shivam Dube',
       'Shreyas Gopal', 'Shamar Joseph', 'Siddharth Kaul',
       'Shivil Kaushik', 'Sarabjit Ladda', 'Sandeep Lamichhane',
       'Sudhesan Midhun', 'Shahbaz Nadeem', 'Sumit Narwal', 'Sachin Rana',
       'Suraj Randiv', 'Sandeep Warrier', 'Sunny Sohal', 'Sreesanth',
       'Sridharan Sriram', 'Sudeep Tyagi', 'Vidyut Sivaramakrishnan',
       'Sean Abbott', 'Swapnil Asnodkar', 'Sanjay Bangar', 'Shivam Dubey',
       'Shadab Jakati', 'Sunil Joshi', 'Scott Styris', 'Shrikant Wagh',
       'Sourav Ganguly', 'Scott Kuggeleijn', 'Siddharth Chitnis',
       'Shai Hope', 'Siddhesh Lad', 'Shane Bond', 'Shaun Marsh',
       'Sherfane Rutherford', 'Spencer Johnson', 'Shalabh Srivastava',
       'Suresh Raina', 'Shaik Rasheed', 'Siddharth Trivedi',
       'Shane Warne', 'Scott Boland', 'Sam Curran', 'Shane Harwood',
       'Simon Katich', 'Shaun Pollock', 'Sachithra Senanayake',
       'Sarfaraz Khan', 'Shardul Thakur', 'Shimron Hetmyer',
       'Stephen Fleming', 'Shreevats Goswami', 'Sheldon Jackson',
       'Sunil Narine', 'Steve Smith', 'Sachin Tendulkar', 'Shane Watson',
       'Shubham Agarwal', 'Sheldon Cottrell', 'Shreyas Iyer',
       'Shrikant Mundhe', 'Suyash Prabhudessai', 'Soumya Sarkar',
       'Sufiyan Shaikh', 'Saurabh Tiwary', 'Sisanda Magala',
       'Sanath Jayasuriya', 'Stuart Binny', 'Sanju Samson',
       'Sam Billings', 'Shaun Tait', 'Shams Mulani', 'Sachin Baby',
       'Salman Butt', 'Sameer Rizvi', 'Sandeep Sharma', 'Sanvir Singh',
       'Saurav Chauhan', 'Sediqullah Atal', 'Shahbaz Ahmed',
       'Shahid Afridi', 'Shakib Al Hasan', 'Shashank Singh',
       'Shivam Mavi', 'Shivam Sharma', 'Shivam Singh', 'Shoaib Ahmed',
       'Shoaib Akhtar', 'Shoaib Malik', 'Shubman Gill', 'Sikandar Raza',
       'Simarjeet Singh', 'Sohail Tanvir', 'Sumit Kumar', 'Sunny Gupta',
       'Sunny Singh', 'Suryansh Shedge', 'Suyash Sharma', 'Swapnil Singh',
       'Tom Banton', 'Tyron Henderson', 'Tom Kohler-Cadmore',
       'Taruwar Kohli', 'T. Natarajan', 'Tabraiz Shamsi',
       'Tristan Stubbs', 'Tatenda Taibu', 'Thilan Thushara',
       'Trent Boult', 'Tim Paine', 'Tim Southee', 'Tim David',
       'Tom Curran', 'Tim Seifert', 'Tirumalasetti Suman',
       'Tillakaratne Dilshan', 'Travis Head', 'Tanmay Srivastava',
       'T. P. Sudhindra', 'Travis Birt', 'Tymal Mills',
       'Tushar Deshpande', 'Tanush Kotian', 'Tejas Baroka', 'Tilak Varma',
       'Uday Kaul', 'Udit Birla', 'Unmukt Chand', 'Usman Khawaja',
       'Umesh Yadav', 'Umar Gul', 'Umran Malik', 'Urvil Patel',
       'Vidwath Kaverappa', 'Virat Kohli', 'Vikas Nigam',
       'Vishwa Pratap Singh', 'Vyshak Vijaykumar', 'Virender Sehwag',
       'Vijay Shankar', 'Vaibhav Suryavanshi', 'Vijayakanth Viyaskanth',
       'Vaibhav Arora', 'Vijay Zol', 'Varun Aaron', 'Venkatesh Iyer',
       'V. R. V. Singh', 'Vikramjeet Malik', 'Vinayak Yeligati',
       'V. V. S. Laxman', 'V. Y. Mahesh', 'Vijaykumar Vyshak',
       'Virat Singh', 'Vishnu Vinod', 'Vivrant Sharma', 'Wasim Jaffer',
       "William O'Rourke", 'Wilkin Mota', 'Wayne Parnell', 'Will Jacks',
       'Wriddhiman Saha', 'Chaminda Vaas', 'Washington Sundar',
       'Xavier Thalaivan Sargunam', 'Xavier Bartlett',
       'Yalaka Gnaneswara Rao', 'Yogesh Nagar', 'Yarra Prithvi Raj',
       'Yalaka Venugopal Rao', 'Yusuf Abdulla', 'Yashasvi Jaiswal',
       'Yusuf Pathan', 'Yuzvendra Chahal', 'Yash Dhull',
       'Yogesh Takawale', 'Yash Dayal', 'Yash Thakur', 'Yashpal Singh',
       'Younis Khan', 'Yudhvir Singh', 'Yuvraj Singh', 'Zaheer Khan',
       'Zeeshan Ansari'], dtype=object)

In [39]:
player_mapping = {
    'A Ashish Reddy': 'Ashish Reddy',
    'A Badoni': 'Ayush Badoni',
    'A Chandila': 'Ajit Chandila',
    'A Chopra': 'Aakash Chopra',
    'A Choudhary': 'Aniket Choudhary',
    'A Dananjaya': 'Akila Dananjaya',
    'A Flintoff': 'Andrew Flintoff',
    'A Kamboj': 'Anshul Kamboj',
    'A Kumble': 'Anil Kumble',
    'A Manohar': 'Abhinav Manohar',
    'A Mhatre': 'Ayush Mhatre',
    'A Mishra': 'Amit Mishra',
    'A Mithun': 'Abhimanyu Mithun',
    'A Mukund': 'Abhinav Mukund',
    'A Nehra': 'Ashish Nehra',
    'A Nel': 'André Nel',
    'A Nortje': 'Anrich Nortje',
    'A Raghuvanshi': 'Angkrish Raghuvanshi',
    'A Singh': 'Anureet Singh',
    'A Symonds': 'Andrew Symonds',
    'A Tomar': 'Anshuman Tomar',
    'A Uniyal': 'Amit Uniyal',
    'A Zampa': 'Adam Zampa',
    'AA Bilakhia': 'Akshath Bilakhia',
    'AA Chavan': 'Ankeet Chavan',
    'AA Jhunjhunwala': 'Abhishek Jhunjhunwala',
    'AA Kazi': 'Abrar Kazi',
    'AA Kulkarni': 'Arshin Kulkarni',
    'AA Noffke': 'Ashley Noffke',
    'AB Agarkar': 'Ajit Agarkar',
    'AB Barath': 'Adrian Barath',
    'AB Dinda': 'Ashoke Dinda',
    'AB McDonald': 'Andrew McDonald',
    'AB de Villiers': 'AB de Villiers',
    'AC Blizzard': 'Aiden Blizzard',
    'AC Gilchrist': 'Adam Gilchrist',
    'AC Thomas': 'Alfonso Thomas',
    'AC Voges': 'Adam Voges',
    'AD Hales': 'Alex Hales',
    'AD Mascarenhas': 'Dimitri Mascarenhas',
    'AD Mathews': 'Angelo Mathews',
    'AD Nath': 'Akshdeep Nath',
    'AD Russell': 'Andre Russell',
    'AF Milne': 'Adam Milne',
    'AG Murtaza': 'Ali Murtaza',
    'AG Paunikar': 'Amit Paunikar',
    'AJ Finch': 'Aaron Finch',
    'AJ Hosein': 'Akeal Hosein',
    'AJ Turner': 'Ashton Turner',
    'AJ Tye': 'Andrew Tye',
    'AK Markram': 'Aiden Markram',
    'AL Menaria': 'Ashok Menaria',
    'AM Nayar': 'Abhishek Nayar',
    'AM Rahane': 'Ajinkya Rahane',
    'AM Salvi': 'Aavishkar Salvi',
    'AN Ahmed': 'Abu Nechim',
    'AN Ghosh': 'Arindam Ghosh',
    'AP Dole': 'Aditya Dole',
    'AP Majumdar': 'Anustup Majumdar',
    'AP Tare': 'Aditya Tare',
    'AR Bawne': 'Ankit Bawne',
    'AR Patel': 'Axar Patel',
    'AS Joseph': 'Alzarri Joseph',
    'AS Rajpoot': 'Ankit Rajpoot',
    'AS Raut': 'Abhishek Raut',
    'AS Roy': 'Anukul Roy',
    'AS Yadav': 'Suryakumar Yadav',
    'AT Carey': 'Alex Carey',
    'AT Rayudu': 'Ambati Rayudu',
    'AU Rashid': 'Adil Rashid',
    'AUK Pathan': 'Asad Pathan',
    'B Akhil': 'Balachandra Akhil',
    'B Chipli': 'Bharat Chipli',
    'B Geeves': 'Brett Geeves',
    'B Indrajith': 'Baba Indrajith',
    'B Kumar': 'Bhuvaneshwar Kumar',
    'B Laughlin': 'Ben Laughlin',
    'B Lee': 'Brett Lee',
    'B Sai Sudharsan': 'Sai Sudharsan',
    'B Stanlake': 'Billy Stanlake',
    'B Sumanth': 'Bodanapu Sumanth',
    'BA Bhatt': 'Bhargav Bhatt',
    'BA Stokes': 'Ben Stokes',
    'BAW Mendis': 'Ajantha Mendis',
    'BB McCullum': 'Brendon McCullum',
    'BB Samantray': 'Biplab Samantray',
    'BB Sran': 'Barinder Sran',
    'BCJ Cutting': 'Ben Cutting',
    'BE Hendricks': 'Beuran Hendricks',
    'BJ Haddin': 'Brad Haddin',
    'BJ Hodge': 'Brad Hodge',
    'BJ Rohrer': 'Ben Rohrer',
    'BKG Mendis': 'Jeevan Mendis',
    'BMAJ Mendis': 'Jeevan Mendis',
    'BR Dunk': 'Ben Dunk',
    'BR Sharath': 'Barafe Sharath',
    'BW Hilfenhaus': 'Ben Hilfenhaus',
    'C Bosch': 'Corbin Bosch',
    'C Ganapathy': 'Chandrasekar Ganapathy',
    'C Green': 'Cameron Green',
    'C Madan': 'Chandan Madan',
    'C Munro': 'Colin Munro',
    'C Nanda': 'Chetan Nanda',
    'C Sakariya': 'Chetan Sakariya',
    'C de Grandhomme': 'Colin de Grandhomme',
    'CA Ingram': 'Colin Ingram',
    'CA Lynn': 'Chris Lynn',
    'CA Pujara': 'Cheteshwar Pujara',
    'CH Gayle': 'Chris Gayle',
    'CH Morris': 'Chris Morris',
    'CJ Anderson': 'Corey Anderson',
    'CJ Dala': 'Junior Dala',
    'CJ Ferguson': 'Callum Ferguson',
    'CJ Green': 'Chris Green',
    'CJ Jordan': 'Chris Jordan',
    'CJ McKay': 'Clint McKay',
    'CK Kapugedera': 'Chamara Kapugedera',
    'CK Langeveldt': 'Charl Langeveldt',
    'CL White': 'Cameron White',
    'CM Gautam': 'C. M. Gautam',
    'CR Brathwaite': 'Carlos Brathwaite',
    'CR Woakes': 'Chris Woakes',
    'CRD Fernando': 'Dilhara Fernando',
    'CV Varun': 'Varun Chakravarthy',
    'D Brevis': 'Dewald Brevis',
    'D Ferreira': 'Donovan Ferreira',
    'D Jansen': 'Duan Jansen',
    'D Kalyankrishna': 'Doddapaneni Kalyankrishna',
    'D Padikkal': 'Devdutt Padikkal',
    'D Pretorius': 'Dwaine Pretorius',
    'D Salunkhe': 'Dinesh Salunkhe',
    'D Wiese': 'David Wiese',
    'D du Preez': 'Dillon du Preez',
    'DA Miller': 'David Miller',
    'DA Warner': 'David Warner',
    'DAJ Bracewell': 'Doug Bracewell',
    'DB Das': 'Debabrata Das',
    'DB Ravi Teja': 'Dwaraka Ravi Teja',
    'DE Bollinger': 'Doug Bollinger',
    'DG Nalkande': 'Darshan Nalkande',
    'DH Yagnik': 'Dishant Yagnik',
    'DJ Bravo': 'Dwayne Bravo',
    'DJ Harris': 'Daniel Harris',
    'DJ Hooda': 'Deepak Hooda',
    'DJ Hussey': 'David Hussey',
    'DJ Jacobs': 'Davy Jacobs',
    'DJ Malan': 'Dawid Malan',
    'DJ Mitchell': 'Daryl Mitchell',
    'DJ Muthuswami': 'Domnic Muthuswami',
    'DJ Thornely': 'Dominic Thornely',
    'DJ Willey': 'David Willey',
    'DJG Sammy': 'Darren Sammy',
    'DJM Short': "D'Arcy Short",
    'DL Chahar': 'Deepak Chahar',
    'DL Vettori': 'Daniel Vettori',
    'DM Bravo': 'Darren Bravo',
    'DNT Zoysa': 'Nuwan Zoysa',
    'DP Conway': 'Devon Conway',
    'DP Nannes': 'Dirk Nannes',
    'DP Vijaykumar': 'Doddapaneni Vijaykumar',
    'DPMD Jayawardene': 'Mahela Jayawardene',
    'DR Martyn': 'Damien Martyn',
    'DR Sams': 'Daniel Sams',
    'DR Shorey': 'Dhruv Shorey',
    'DR Smith': 'Dwayne Smith',
    'DS Kulkarni': 'Dhawal Kulkarni',
    'DS Lehmann': 'Darren Lehmann',
    'DS Rathi': 'Dhruv Rathi',
    'DT Christian': 'Dan Christian',
    'DT Patil': 'Dinesh Patil',
    'DW Steyn': 'Dale Steyn',
    'E Lewis': 'Evin Lewis',
    'E Malinga': 'Lasith Malinga',
    'EJG Morgan': 'Eoin Morgan',
    'ER Dwivedi': 'Eklavya Dwivedi',
    'F Behardien': 'Farhaan Behardien',
    'F du Plessis': 'Faf du Plessis',
    'FA Allen': 'Fabian Allen',
    'FH Edwards': 'Fidel Edwards',
    'FY Fazal': 'Faiz Fazal',
    'G Coetzee': 'Gerald Coetzee',
    'G Gambhir': 'Gautam Gambhir',
    'GB Hogg': 'Brad Hogg',
    'GC Smith': 'Graeme Smith',
    'GC Viljoen': 'Hardus Viljoen',
    'GD McGrath': 'Glenn McGrath',
    'GD Phillips': 'Glenn Phillips',
    'GH Vihari': 'Hanuma Vihari',
    'GHS Garton': 'George Garton',
    'GJ Bailey': 'George Bailey',
    'GJ Maxwell': 'Glenn Maxwell',
    'GR Napier': 'Graham Napier',
    'GS Sandhu': 'Gurinder Sandhu',
    'H Das': 'Halhadar Das',
    'H Klaasen': 'Heinrich Klaasen',
    'H Sharma': 'Himanshu Sharma',
    'HC Brook': 'Harry Brook',
    'HE van der Dussen': 'Rassie van der Dussen',
    'HF Gurney': 'Harry Gurney',
    'HH Gibbs': 'Herschelle Gibbs',
    'HH Pandya': 'Hardik Pandya',
    'HM Amla': 'Hashim Amla',
    'HR Shokeen': 'Hrithik Shokeen',
    'HV Patel': 'Harshal Patel',
    'I Malhotra': 'Ishan Malhotra',
    'I Sharma': 'Ishant Sharma',
    'I Udana': 'Isuru Udana',
    'IC Pandey': 'Ishwar Pandey',
    'IC Porel': 'Ishan Porel',
    'IK Pathan': 'Irfan Pathan',
    'IR Jaggi': 'Ishank Jaggi',
    'IS Sodhi': 'Ish Sodhi',
    'J Arunkumar': 'Jagadeesh Arunkumar',
    'J Botha': 'Johan Botha',
    'J Fraser-McGurk': 'Jake Fraser-McGurk',
    'J Little': 'Joshua Little',
    'J Overton': 'Jamie Overton',
    'J Suchith': 'Jagadeesha Suchith',
    'J Syed Mohammad': 'Jamaluddin Syed Mohammad',
    'J Theron': 'Juan Theron',
    'J Yadav': 'Jayant Yadav',
    'JA Morkel': 'Albie Morkel',
    'JA Richardson': 'Jhye Richardson',
    'JC Archer': 'Jofra Archer',
    'JC Buttler': 'Jos Buttler',
    'JD Ryder': 'Jesse Ryder',
    'JD Unadkat': 'Jaydev Unadkat',
    'JDP Oram': 'Jacob Oram',
    'JDS Neesham': 'Jimmy Neesham',
    'JE Root': 'Joe Root',
    'JE Taylor': 'Jerome Taylor',
    'JEC Franklin': 'James Franklin',
    'JG Bethell': 'Jacob Bethell',
    'JH Kallis': 'Jacques Kallis',
    'JJ Bumrah': 'Jasprit Bumrah',
    'JJ Roy': 'Jason Roy',
    'JJ van der Wath': 'Johan van der Wath',
    'JL Denly': 'Joe Denly',
    'JL Pattinson': 'James Pattinson',
    'JM Bairstow': 'Jonny Bairstow',
    'JM Kemp': 'Justin Kemp',
    'JM Sharma': 'Jitesh Sharma',
    'JO Holder': 'Jason Holder',
    'JP Behrendorff': 'Jason Behrendorff',
    'JP Duminy': 'JP Duminy',
    'JP Faulkner': 'James Faulkner',
    'JP Inglis': 'Josh Inglis',
    'JPR Scantlebury-Searles': 'Javon Searles',
    'JR Hazlewood': 'Josh Hazlewood',
    'JR Hopes': 'James Hopes',
    'JR Philippe': 'Josh Philippe',
    'JW Hastings': 'John Hastings',
    'K Goel': 'Karan Goel',
    'K Gowtham': 'Krishnappa Gowtham',
    'K Kartikeya': 'Kumar Kartikeya',
    'K Khejroliya': 'Kulwant Khejroliya',
    'K Rabada': 'Kagiso Rabada',
    'K Santokie': 'Krishmar Santokie',
    'K Upadhyay': 'Krishnakumar Upadhyay',
    'K Yadav': 'Kuldeep Yadav',
    'KA Jamieson': 'Kyle Jamieson',
    'KA Maharaj': 'Keshav Maharaj',
    'KA Pollard': 'Kieron Pollard',
    'KAJ Roach': 'Kemar Roach',
    'KB Arun Karthik': 'Arun Karthik',
    'KC Cariappa': 'K. C. Cariappa',
    'KC Sangakkara': 'Kumar Sangakkara',
    'KD Karthik': 'Dinesh Karthik',
    'KH Pandya': 'Krunal Pandya',
    'KJ Abbott': 'Kyle Abbott',
    'KK Ahmed': 'Khaleel Ahmed',
    'KK Cooper': 'Kevon Cooper',
    'KK Nair': 'Karun Nair',
    'KL Nagarkoti': 'Kamlesh Nagarkoti',
    'KL Rahul': 'KL Rahul',
    'KM Asif': 'KM Asif',
    'KM Jadhav': 'Kedar Jadhav',
    'KMA Paul': 'Keemo Paul',
    'KMDN Kulasekara': 'Nuwan Kulasekara',
    'KP Appanna': 'Kotarangada Appanna',
    'KP Pietersen': 'Kevin Pietersen',
    'KR Mayers': 'Kyle Mayers',
    'KR Sen': 'Kuldeep Sen',
    'KS Bharat': 'Srikar Bharat',
    'KS Rathore': 'Kunal Singh Rathore',
    'KS Sharma': 'Karn Sharma',
    'KS Williamson': 'Kane Williamson',
    'KT Maphaka': 'Kwena Maphaka',
    'KV Sharma': 'Karn Sharma',
    'KW Richardson': 'Kane Richardson',
    'L Ablish': 'Love Ablish',
    'L Balaji': 'Lakshmipathy Balaji',
    'L Ngidi': 'Lungi Ngidi',
    'L Ronchi': 'Luke Ronchi',
    'L Wood': 'Luke Wood',
    'LA Carseldine': 'Lee Carseldine',
    'LA Pomersbach': 'Luke Pomersbach',
    'LB Williams': 'Lizaad Williams',
    'LE Plunkett': 'Liam Plunkett',
    'LH Ferguson': 'Lockie Ferguson',
    'LI Meriwala': 'Lukman Meriwala',
    'LJ Wright': 'Luke Wright',
    'LMP Simmons': 'Lendl Simmons',
    'LPC Silva': 'Chamara Silva',
    'LR Shukla': 'Laxmi Ratan Shukla',
    'LRPL Taylor': 'Ross Taylor',
    'LS Livingstone': 'Liam Livingstone',
    'M Ashwin': 'Murugan Ashwin',
    'M Jansen': 'Marco Jansen',
    'M Kaif': 'Mohammad Kaif',
    'M Kartik': 'Murali Kartik',
    'M Klinger': 'Michael Klinger',
    'M Manhas': 'Mithun Manhas',
    'M Markande': 'Mayank Markande',
    'M Morkel': 'Morne Morkel',
    'M Muralitharan': 'Muttiah Muralitharan',
    'M Ntini': 'Makhaya Ntini',
    'M Pathirana': 'Matheesha Pathirana',
    'M Prasidh Krishna': 'Prasidh Krishna',
    'M Rawat': 'Mahesh Rawat',
    'M Shahrukh Khan': 'Shahrukh Khan',
    'M Siddharth': 'Manimaran Siddharth',
    'M Theekshana': 'Maheesh Theekshana',
    'M Tiwari': 'Manoj Tiwary',
    'M Vijay': 'Murali Vijay',
    'M Vohra': 'Manan Vohra',
    'M de Lange': 'Marchant de Lange',
    'MA Agarwal': 'Mayank Agarwal',
    'MA Khote': 'Musavir Khote',
    'MA Starc': 'Mitchell Starc',
    'MA Wood': 'Mark Wood',
    'MB Parmar': 'Mohnish Parmar',
    'MC Henriques': 'Moises Henriques',
    'MC Juneja': 'Manpreet Juneja',
    'MD Mishra': 'Mohnish Mishra',
    'MD Shanaka': 'Dasun Shanaka',
    'MDKJ Perera': 'Kusal Perera',
    'MEK Hussey': 'Michael Hussey',
    'MF Maharoof': 'Farveez Maharoof',
    'MG Bracewell': 'Michael Bracewell',
    'MG Johnson': 'Mitchell Johnson',
    'MG Neser': 'Michael Neser',
    'MJ Clarke': 'Michael Clarke',
    'MJ Guptill': 'Martin Guptill',
    'MJ Henry': 'Matt Henry',
    'MJ Lumb': 'Michael Lumb',
    'MJ McClenaghan': 'Mitchell McClenaghan',
    'MJ Owen': 'Mitchell Owen',
    'MJ Santner': 'Mitchell Santner',
    'MJ Suthar': 'Manav Suthar',
    'MK Lomror': 'Mahipal Lomror',
    'MK Pandey': 'Manish Pandey',
    'MK Tiwary': 'Manoj Tiwary',
    'ML Hayden': 'Matthew Hayden',
    'MM Ali': 'Moeen Ali',
    'MM Patel': 'Munaf Patel',
    'MM Sharma': 'Mohit Sharma',
    'MN Samuels': 'Marlon Samuels',
    'MN van Wyk': 'Morne van Wyk',
    'MP Breetzke': 'Matthew Breetzke',
    'MP Stoinis': 'Marcus Stoinis',
    'MP Yadav': 'Mayank Yadav',
    'MR Marsh': 'Mitchell Marsh',
    'MS Bhandage': 'Manoj Bhandage',
    'MS Bisla': 'Manvinder Bisla',
    'MS Dhoni': 'MS Dhoni',
    'MS Gony': 'Manpreet Gony',
    'MS Wade': 'Matthew Wade',
    'MV Boucher': 'Mark Boucher',
    'MW Short': 'Matthew Short',
    'N Burger': 'Nandre Burger',
    'N Jagadeesan': 'Narayan Jagadeesan',
    'N Pooran': 'Nicholas Pooran',
    'N Rana': 'Nitish Rana',
    'N Saini': 'Navdeep Saini',
    'N Thushara': 'Nuwan Thushara',
    'N Wadhera': 'Nehal Wadhera',
    'NA Saini': 'Navdeep Saini',
    'NB Singh': 'Nikhil Singh',
    'ND Doshi': 'Nayan Doshi',
    'NJ Maddinson': 'Nic Maddinson',
    'NJ Rimmington': 'Nathan Rimmington',
    'NK Patel': 'Niraj Patel',
    'NL McCullum': 'Nathan McCullum',
    'NLTC Perera': 'Thisara Perera',
    'NM Coulter-Nile': 'Nathan Coulter-Nile',
    'NS Naik': 'Nikhil Naik',
    'NT Ellis': 'Nathan Ellis',
    'NV Ojha': 'Naman Ojha',
    'O Thomas': 'Oshane Thomas',
    'OA Shah': 'Owais Shah',
    'OC McCoy': 'Obed McCoy',
    'OF Smith': 'Odean Smith',
    'P Amarnath': 'Palani Amarnath',
    'P Awana': 'Parvinder Awana',
    'P Chopra': 'Prashant Chopra',
    'P Dogra': 'Paras Dogra',
    'P Dubey': 'Praveen Dubey',
    'P Kumar': 'Praveen Kumar',
    'P Negi': 'Pawan Negi',
    'P Parameswaran': 'Prasanth Parameswaran',
    'P Prasanth': 'Padmanabhan Prasanth',
    'P Ray Barman': 'Prayas Ray Barman',
    'P Sahu': 'Pardeep Sahu',
    'P Simran Singh': 'Prabhsimran Singh',
    'P Suyal': 'Pawan Suyal',
    'PA Patel': 'Parthiv Patel',
    'PA Reddy': 'Akshath Reddy',
    'PBB Rajapaksa': 'Bhanuka Rajapaksa',
    'PC Valthaty': 'Paul Valthaty',
    'PD Collingwood': 'Paul Collingwood',
    'PD Salt': 'Phil Salt',
    'PH Solanki': 'Prashant Solanki',
    'PHKD Mendis': 'Kamindu Mendis',
    'PJ Cummins': 'Pat Cummins',
    'PJ Sangwan': 'Pradeep Sangwan',
    'PK Garg': 'Priyam Garg',
    'PM Sarvesh Kumar': 'Sarvesh Kumar',
    'PN Mankad': 'Prerak Mankad',
    'PP Chawla': 'Piyush Chawla',
    'PP Ojha': 'Pragyan Ojha',
    'PP Shaw': 'Prithvi Shaw',
    'PR Shah': 'Pinal Shah',
    'PSP Handscomb': 'Peter Handscomb',
    'PV Tambe': 'Pravin Tambe',
    'PVD Chameera': 'Dushmantha Chameera',
    'PVSN Raju': 'Venugopal Rao',
    'PWA Mulder': 'Wiaan Mulder',
    'PWH de Silva': 'Wanindu Hasaranga',
    'Q de Kock': 'Quinton de Kock',
    'R Ashwin': 'Ravichandran Ashwin',
    'R Bhatia': 'Rajat Bhatia',
    'R Bishnoi': 'Ravi Bishnoi',
    'R Dhawan': 'Rishi Dhawan',
    'R Dravid': 'Rahul Dravid',
    'R Goyal': 'Ravi Goyal',
    'R McLaren': 'Ryan McLaren',
    'R Minz': 'Robin Minz',
    'R Ninan': 'Ryan Ninan',
    'R Parag': 'Riyan Parag',
    'R Powell': 'Rovman Powell',
    'R Rampaul': 'Ravi Rampaul',
    'R Ravindra': 'Rachin Ravindra',
    'R Sai Kishore': 'Ravisrinivasan Sai Kishore',
    'R Sanjay Yadav': 'Sanjay Yadav',
    'R Sathish': 'Rajagopal Sathish',
    'R Sharma': 'Rahul Sharma',
    'R Shepherd': 'Romario Shepherd',
    'R Shukla': 'Rahul Shukla',
    'R Tewatia': 'Rahul Tewatia',
    'R Vinay Kumar': 'Vinay Kumar',
    'RA Bawa': 'Raj Bawa',
    'RA Jadeja': 'Ravindra Jadeja',
    'RA Shaikh': 'Rahil Shaikh',
    'RA Tripathi': 'Rahul Tripathi',
    'RD Chahar': 'Rahul Chahar',
    'RD Gaikwad': 'Ruturaj Gaikwad',
    'RD Rickelton': 'Ryan Rickelton',
    'RE Levi': 'Richard Levi',
    'RE van der Merwe': 'Roelof van der Merwe',
    'RG More': 'Ronit More',
    'RG Sharma': 'Rohit Sharma',
    'RJ Gleeson': 'Richard Gleeson',
    'RJ Harris': 'Ryan Harris',
    'RJ Peterson': 'Robin Peterson',
    'RJ Quiney': 'Rob Quiney',
    'RJW Topley': 'Reece Topley',
    'RK Bhui': 'Ricky Bhui',
    'RK Singh': 'Rinku Singh',
    'RM Patidar': 'Rajat Patidar',
    'RN ten Doeschate': 'Ryan ten Doeschate',
    'RP Meredith': 'Riley Meredith',
    'RP Singh': 'R. P. Singh',
    'RR Bhatkal': 'Raju Bhatkal',
    'RR Bose': 'Ranadeb Bose',
    'RR Pant': 'Rishabh Pant',
    'RR Powar': 'Ramesh Powar',
    'RR Raje': 'Rohan Raje',
    'RR Rossouw': 'Rilee Rossouw',
    'RR Sarwan': 'Ramnaresh Sarwan',
    'RS Bopara': 'Ravi Bopara',
    'RS Gavaskar': 'Rohan Gavaskar',
    'RS Hangargekar': 'Rajvardhan Hangargekar',
    'RS Sodhi': 'Reetinder Sodhi',
    'RT Ponting': 'Ricky Ponting',
    'RV Gomez': 'Raiphi Gomez',
    'RV Patel': 'Ripal Patel',
    'RV Uthappa': 'Robin Uthappa',
    'RW Price': 'Ray Price',
    'S Anirudha': 'Anirudha Srikkanth',
    'S Aravind': 'Sreenath Aravind',
    'S Badree': 'Samuel Badree',
    'S Badrinath': 'Subramaniam Badrinath',
    'S Chanderpaul': 'Shivnarine Chanderpaul',
    'S Dhawan': 'Shikhar Dhawan',
    'S Dube': 'Shivam Dube',
    'S Gopal': 'Shreyas Gopal',
    'S Joseph': 'Shamar Joseph',
    'S Kaul': 'Siddharth Kaul',
    'S Kaushik': 'Shivil Kaushik',
    'S Ladda': 'Sarabjit Ladda',
    'S Lamichhane': 'Sandeep Lamichhane',
    'S Midhun': 'Sudhesan Midhun',
    'S Nadeem': 'Shahbaz Nadeem',
    'S Narwal': 'Sumit Narwal',
    'S Rana': 'Sachin Rana',
    'S Randiv': 'Suraj Randiv',
    'S Sandeep Warrier': 'Sandeep Warrier',
    'S Sohal': 'Sunny Sohal',
    'S Sreesanth': 'Sreesanth',
    'S Sriram': 'Sridharan Sriram',
    'S Tyagi': 'Sudeep Tyagi',
    'S Vidyut': 'Vidyut Sivaramakrishnan',
    'SA Abbott': 'Sean Abbott',
    'SA Asnodkar': 'Swapnil Asnodkar',
    'SA Yadav': 'Suryakumar Yadav',
    'SB Bangar': 'Sanjay Bangar',
    'SB Dubey': 'Shivam Dubey',
    'SB Jakati': 'Shadab Jakati',
    'SB Joshi': 'Sunil Joshi',
    'SB Styris': 'Scott Styris',
    'SB Wagh': 'Shrikant Wagh',
    'SC Ganguly': 'Sourav Ganguly',
    'SC Kuggeleijn': 'Scott Kuggeleijn',
    'SD Chitnis': 'Siddharth Chitnis',
    'SD Hope': 'Shai Hope',
    'SD Lad': 'Siddhesh Lad',
    'SE Bond': 'Shane Bond',
    'SE Marsh': 'Shaun Marsh',
    'SE Rutherford': 'Sherfane Rutherford',
    'SH Johnson': 'Spencer Johnson',
    'SJ Srivastava': 'Shalabh Srivastava',
    'SK Raina': 'Suresh Raina',
    'SK Rasheed': 'Shaik Rasheed',
    'SK Trivedi': 'Siddharth Trivedi',
    'SK Warne': 'Shane Warne',
    'SL Malinga': 'Lasith Malinga',
    'SM Boland': 'Scott Boland',
    'SM Curran': 'Sam Curran',
    'SM Harwood': 'Shane Harwood',
    'SM Katich': 'Simon Katich',
    'SM Pollock': 'Shaun Pollock',
    'SMSM Senanayake': 'Sachithra Senanayake',
    'SN Khan': 'Sarfaraz Khan',
    'SN Thakur': 'Shardul Thakur',
    'SO Hetmyer': 'Shimron Hetmyer',
    'SP Fleming': 'Stephen Fleming',
    'SP Goswami': 'Shreevats Goswami',
    'SP Jackson': 'Sheldon Jackson',
    'SP Narine': 'Sunil Narine',
    'SPD Smith': 'Steve Smith',
    'SR Tendulkar': 'Sachin Tendulkar',
    'SR Watson': 'Shane Watson',
    'SS Agarwal': 'Shubham Agarwal',
    'SS Cottrell': 'Sheldon Cottrell',
    'SS Iyer': 'Shreyas Iyer',
    'SS Mundhe': 'Shrikant Mundhe',
    'SS Prabhudessai': 'Suyash Prabhudessai',
    'SS Sarkar': 'Soumya Sarkar',
    'SS Shaikh': 'Sufiyan Shaikh',
    'SS Tiwary': 'Saurabh Tiwary',
    'SSB Magala': 'Sisanda Magala',
    'ST Jayasuriya': 'Sanath Jayasuriya',
    'STR Binny': 'Stuart Binny',
    'SV Samson': 'Sanju Samson',
    'SW Billings': 'Sam Billings',
    'SW Tait': 'Shaun Tait',
    'SZ Mulani': 'Shams Mulani',
    'T Banton': 'Tom Banton',
    'T Henderson': 'Tyron Henderson',
    'T Kohler-Cadmore': 'Tom Kohler-Cadmore',
    'T Kohli': 'Taruwar Kohli',
    'T Natarajan': 'T. Natarajan',
    'T Shamsi': 'Tabraiz Shamsi',
    'T Stubbs': 'Tristan Stubbs',
    'T Taibu': 'Tatenda Taibu',
    'T Thushara': 'Thilan Thushara',
    'TA Boult': 'Trent Boult',
    'TD Paine': 'Tim Paine',
    'TG Southee': 'Tim Southee',
    'TH David': 'Tim David',
    'TK Curran': 'Tom Curran',
    'TL Seifert': 'Tim Seifert',
    'TL Suman': 'Tirumalasetti Suman',
    'TM Dilshan': 'Tillakaratne Dilshan',
    'TM Head': 'Travis Head',
    'TM Srivastava': 'Tanmay Srivastava',
    'TP Sudhindra': 'T. P. Sudhindra',
    'TR Birt': 'Travis Birt',
    'TS Mills': 'Tymal Mills',
    'TU Deshpande': 'Tushar Deshpande',
    'U Kaul': 'Uday Kaul',
    'UA Birla': 'Udit Birla',
    'UBT Chand': 'Unmukt Chand',
    'UT Khawaja': 'Usman Khawaja',
    'UT Yadav': 'Umesh Yadav',
    'V Kaverappa': 'Vidwath Kaverappa',
    'V Kohli': 'Virat Kohli',
    'V Nigam': 'Vikas Nigam',
    'V Pratap Singh': 'Vishwa Pratap Singh',
    'V Puthur': 'Vyshak Vijaykumar',
    'V Sehwag': 'Virender Sehwag',
    'V Shankar': 'Vijay Shankar',
    'V Suryavanshi': 'Vaibhav Suryavanshi',
    'V Viyaskanth': 'Vijayakanth Viyaskanth',
    'VG Arora': 'Vaibhav Arora',
    'VH Zol': 'Vijay Zol',
    'VR Aaron': 'Varun Aaron',
    'VR Iyer': 'Venkatesh Iyer',
    'VRV Singh': 'V. R. V. Singh',
    'VS Malik': 'Vikramjeet Malik',
    'VS Yeligati': 'Vinayak Yeligati',
    'VVS Laxman': 'V. V. S. Laxman',
    'VY Mahesh': 'V. Y. Mahesh',
    'W Jaffer': 'Wasim Jaffer',
    "W O'Rourke": "William O'Rourke",
    'WA Mota': 'Wilkin Mota',
    'WD Parnell': 'Wayne Parnell',
    'WG Jacks': 'Will Jacks',
    'WP Saha': 'Wriddhiman Saha',
    'WPUJC Vaas': 'Chaminda Vaas',
    'X Thalaivan Sargunam': 'Xavier Thalaivan Sargunam',
    'XC Bartlett': 'Xavier Bartlett',
    'Y Gnaneswara Rao': 'Yalaka Gnaneswara Rao',
    'Y Nagar': 'Yogesh Nagar',
    'Y Prithvi Raj': 'Yarra Prithvi Raj',
    'Y Venugopal Rao': 'Yalaka Venugopal Rao',
    'YA Abdulla': 'Yusuf Abdulla',
    'YBK Jaiswal': 'Yashasvi Jaiswal',
    'YK Pathan': 'Yusuf Pathan',
    'YS Chahal': 'Yuzvendra Chahal',
    'YV Dhull': 'Yash Dhull',
    'YV Takawale': 'Yogesh Takawale',
    'Z Khan': 'Zaheer Khan'
}

In [44]:
raw_data['batter'] = raw_data['batter'].replace(player_mapping)
raw_data['bowler'] = raw_data['bowler'].replace(player_mapping)
raw_data['fielders'] = raw_data['fielders'].replace(player_mapping)
raw_data

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,Sourav Ganguly,1,0,1,Praveen Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,Brendon McCullum,2,0,1,Praveen Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,Brendon McCullum,2,0,0,Praveen Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,Brendon McCullum,2,0,1,Praveen Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,Brendon McCullum,2,0,1,Praveen Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278200,277951,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,2,19.2,Shashank Singh,6,0,1,Josh Hazlewood,1,0,0,0,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278201,277952,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,3,19.3,Shashank Singh,6,6,1,Josh Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278202,277953,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,4,19.4,Shashank Singh,6,4,1,Josh Hazlewood,1,0,4,4,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278203,277954,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,5,19.5,Shashank Singh,6,6,1,Josh Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278204,277955,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,6,19.6,Shashank Singh,6,6,1,Josh Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False

In [45]:
wk_list = raw_data.loc[raw_data['wicket_kind']=='stumped','fielders'].unique()

In [46]:
wk_list

array(['Mark Boucher', 'Kamran Akmal', 'Wriddhiman Saha',
       'Yogesh Takawale', 'Adam Gilchrist', 'Dinesh Karthik',
       'Shreevats Goswami', 'Robin Uthappa', 'MS Dhoni', 'Pinal Shah',
       'Mahesh Rawat', 'Naman Ojha', 'Kumar Sangakkara', 'Aditya Tare',
       'Parthiv Patel', 'Ambati Rayudu', 'AB de Villiers', 'Davy Jacobs',
       'Manvinder Bisla', 'Dishant Yagnik', 'KH Devdhar', 'Navdeep Saini',
       'Brendon McCullum', 'Arun Karthik', 'Kedar Jadhav',
       'Quinton de Kock', 'Gurkeerat Singh', 'C. M. Gautam',
       'Sanju Samson', 'KL Rahul', 'Rishabh Pant', 'Vishnu Vinod',
       'Ishan Kishan', 'Jos Buttler', 'Heinrich Klaasen',
       'Jonny Bairstow', 'Srikar Bharat', 'Sheldon Jackson',
       'Sam Billings', 'Nicholas Pooran', 'Jitesh Sharma', 'Matthew Wade',
       'Prabhsimran Singh', 'Ryan Rickelton', 'Josh Inglis',
       'Tristan Stubbs'], dtype=object)

In [47]:
data["player_role_wicketkeeper"] = data["player"].isin(wk_list).astype(int)

In [48]:
data[data['player_role_wicketkeeper'] == 1]['player'].unique()

array(['AB de Villiers', 'Adam Gilchrist', 'Aditya Tare', 'Ambati Rayudu',
       'Brendon McCullum', 'C. M. Gautam', 'Dishant Yagnik',
       'Davy Jacobs', 'Gurkeerat Singh', 'Heinrich Klaasen',
       'Ishan Kishan', 'Jos Buttler', 'Jonny Bairstow', 'Jitesh Sharma',
       'Josh Inglis', 'Arun Karthik', 'Kumar Sangakkara',
       'Dinesh Karthik', 'KL Rahul', 'Kedar Jadhav', 'Srikar Bharat',
       'Kamran Akmal', 'Mahesh Rawat', 'Manvinder Bisla', 'MS Dhoni',
       'Matthew Wade', 'Mark Boucher', 'Nicholas Pooran', 'Navdeep Saini',
       'Naman Ojha', 'Prabhsimran Singh', 'Parthiv Patel', 'Pinal Shah',
       'Quinton de Kock', 'Ryan Rickelton', 'Rishabh Pant',
       'Robin Uthappa', 'Shreevats Goswami', 'Sheldon Jackson',
       'Sanju Samson', 'Sam Billings', 'Tristan Stubbs', 'Vishnu Vinod',
       'Wriddhiman Saha', 'Yogesh Takawale'], dtype=object)

In [50]:
data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/database_csv.csv",index = False)

In [49]:
data

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,maiden_points,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match,player_role_wicketkeeper
0,548341,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,0.0,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0
1,548346,Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,0.0,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,35.672040,35.67204,35.67204,80.762144,0.0,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,0.000000,0.0,0.0,7.0,0.6,8.0,0
2,548348,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,35.672040,35.67204,35.67204,80.762144,0.0,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,0.000000,0.0,0.0,7.0,0.0,7.0,0
3,548352,Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,0.0,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,35.67204,35.67204,80.762144,0.0,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,0.0,7.0,0.0,6.0,0
4,548356,Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,0.0,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,2012-05-06,5,30.666667,35.67204,35.67204,80.762144,0.0,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,0.0,7.0,0.0,7.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,0.0,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.60000,35.67204,0.000000,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,0.0,11.0,0.0,11.0,0
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.60000,35.67204,0.000000,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,0.0,11.0,0.0,11.0,0
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.00000,35.67204,0.000000,0.2,11.500000,balanced,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,0.0,11.0,0.0,11.0,0
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,0.0,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.60000,35.67204,0.000000,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,0.0,11.0,0.0,11.0,0
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,0.0,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.80000,35.67204,0.000000,0.4,-2.000000,balanced,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,0.0,11.0,0.0,11.0,0

In [61]:
data['match_id'].sort_values().unique().tolist()[1168]

1485779