In [88]:
import numpy as np
import pandas as pd
data = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/half_processed/half_prepared_data.csv")

In [89]:
data['venue'].value_counts()

venue
Wankhede Stadium                                                      2719
Eden Gardens                                                          2125
M Chinnaswamy Stadium                                                 2116
Arun Jaitley Stadium                                                  2099
MA Chidambaram Stadium                                                1991
Rajiv Gandhi International Stadium                                    1772
Sawai Mansingh Stadium                                                1347
Punjab Cricket Association IS Bindra Stadium                          1297
Narendra Modi Stadium                                                 1002
Dubai International Cricket Stadium                                    988
Sheikh Zayed Stadium                                                   788
Dr DY Patil Sports Academy                                             786
Maharashtra Cricket Association Stadium                                746
Sharjah Cricket Stadium                                                594
Brabourne Stadium                                                      567
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium           501
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    374
Subrata Roy Sahara Stadium                                             336
Kingsmead                                                              317
Himachal Pradesh Cricket Association Stadium                           309
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     260
SuperSport Park                                                        249
Saurashtra Cricket Association Stadium                                 203
Holkar Cricket Stadium                                                 188
New Wanderers Stadium                                                  184
Newlands                                                               164
Barabati Stadium                                                       149
JSCA International Stadium Complex                                     148
St George's Park                                                       144
Shaheed Veer Narayan Singh International Stadium                       126
Barsapara Cricket Stadium                                              115
Nehru Stadium                                                          107
Green Park                                                              83
Vidarbha Cricket Association Stadium, Jamtha                            65
De Beers Diamond Oval                                                   62
Buffalo Park                                                            61
OUTsurance Oval                                                         43
Name: count, dtype: int64

In [73]:
venue_map = {

# Eden Gardens
"Eden Gardens, Kolkata": "Eden Gardens",

# Wankhede
"Wankhede Stadium, Mumbai": "Wankhede Stadium",

# Chinnaswamy
"M Chinnaswamy Stadium, Bengaluru": "M Chinnaswamy Stadium",
"M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",

# Kotla / Arun Jaitley
"Feroz Shah Kotla": "Arun Jaitley Stadium",
"Arun Jaitley Stadium, Delhi": "Arun Jaitley Stadium",

# Chepauk
"MA Chidambaram Stadium, Chepauk": "MA Chidambaram Stadium",
"MA Chidambaram Stadium, Chepauk, Chennai": "MA Chidambaram Stadium",
"MA Chidambaram Stadium": "MA Chidambaram Stadium",

# Hyderabad
"Rajiv Gandhi International Stadium, Uppal": "Rajiv Gandhi International Stadium",
"Rajiv Gandhi International Stadium, Uppal, Hyderabad": "Rajiv Gandhi International Stadium",

# Sawai Mansingh
"Sawai Mansingh Stadium, Jaipur": "Sawai Mansingh Stadium",

# Narendra Modi / Motera
"Sardar Patel Stadium, Motera": "Narendra Modi Stadium, Ahmedabad",

# Punjab / Mohali
"Punjab Cricket Association Stadium, Mohali": "Punjab Cricket Association IS Bindra Stadium",
"Punjab Cricket Association IS Bindra Stadium, Mohali": "Punjab Cricket Association IS Bindra Stadium",
"Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh": "Punjab Cricket Association IS Bindra Stadium",

# Ekana
"Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow":
"Ekana Cricket Stadium",

# DY Patil
"Dr DY Patil Sports Academy, Mumbai": "Dr DY Patil Sports Academy",

# Maharashtra Cricket Association
"Maharashtra Cricket Association Stadium, Pune": "Maharashtra Cricket Association Stadium",

# Brabourne
"Brabourne Stadium, Mumbai": "Brabourne Stadium",

# Vizag
"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam":
"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",

# Dharamsala
"Himachal Pradesh Cricket Association Stadium, Dharamsala":
"Himachal Pradesh Cricket Association Stadium",

# Abu Dhabi
"Zayed Cricket Stadium, Abu Dhabi": "Sheikh Zayed Stadium",

# Mullanpur
"Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh":
"Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur",
}

In [74]:
data['venue'] = data['venue'].replace(venue_map)

In [86]:
data['venue'].value_counts()

venue
Wankhede Stadium                                                      2459
Eden Gardens                                                          1916
M Chinnaswamy Stadium                                                 1884
Arun Jaitley Stadium                                                  1875
MA Chidambaram Stadium                                                1774
Rajiv Gandhi International Stadium                                    1558
Sawai Mansingh Stadium                                                1170
Punjab Cricket Association IS Bindra Stadium                          1097
Narendra Modi Stadium                                                  923
Dubai International Cricket Stadium                                    919
Sheikh Zayed Stadium                                                   731
Maharashtra Cricket Association Stadium                                677
Dr DY Patil Sports Academy                                             661
Sharjah Cricket Stadium                                                553
Brabourne Stadium                                                      501
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium           451
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    340
Subrata Roy Sahara Stadium                                             307
Himachal Pradesh Cricket Association Stadium                           290
Kingsmead                                                              258
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     240
SuperSport Park                                                        219
Saurashtra Cricket Association Stadium                                 173
Holkar Cricket Stadium                                                 170
New Wanderers Stadium                                                  167
JSCA International Stadium Complex                                     142
Barabati Stadium                                                       131
Shaheed Veer Narayan Singh International Stadium                       118
Newlands                                                               118
St George's Park                                                       117
Barsapara Cricket Stadium                                              107
Nehru Stadium                                                           96
Green Park                                                              79
Vidarbha Cricket Association Stadium, Jamtha                            60
De Beers Diamond Oval                                                   53
Buffalo Park                                                            51
OUTsurance Oval                                                         40
Name: count, dtype: int64

In [87]:
data.isnull().sum()

match_id                         0
player                           0
runs                             0
balls                            0
fours                            0
sixes                            0
strike_rate                      0
runs_conceded                    0
balls_bowled                     0
wickets                          0
overs                            0
economy                          0
fielding_points                  0
batting_points                   0
batting_bonus                    0
sr_bonus                         0
wicket_bonus                     0
eco_bonus                        0
lbw_bowled_bonus                 0
bowling_points                   0
maiden_points                    0
fantasy_points                   0
team                             0
opponent                         0
venue                            0
city                             0
toss_winner                      0
toss_decision                    0
stage                            0
season                           0
date                             0
player_match_number              0
last3_avg_points                 0
last5_avg_points               578
last10_avg_points             3047
rolling_strike_rate            588
rolling_wickets                578
opponent_avg_points              0
pitch_type                    1481
venue_avg_points                 0
venue_run_factor                 0
batting_contribution_ratio       0
bowling_contribution_ratio       0
player_role                      0
last10_std_points                0
player_consistency_index         0
form_momentum                 3047
bat_pos                        137
boundary_percentage              0
bat_pos_per_match              137
dtype: int64

In [77]:
data = data.drop(columns = ['venue_avg_points','venue_run_factor'])

match_runs = data.groupby("match_id")["runs"].sum().reset_index()
match_runs.rename(columns={"runs": "total_match_runs"}, inplace=True)
match_runs = match_runs.merge(
    data[["match_id", "venue"]].drop_duplicates(),
    on="match_id"
)
venue_avg_runs = match_runs.groupby("venue")["total_match_runs"].mean()
overall_avg_runs = match_runs["total_match_runs"].mean()
venue_run_factor = venue_avg_runs / overall_avg_runs
data["venue_run_factor"] = data["venue"].map(venue_run_factor)
venue_avg = (
    data
    .groupby(["player", "venue"])["fantasy_points"]
    .mean()
    .reset_index(name="venue_avg_points")
)
data = data.merge(
    venue_avg,
    on=["player", "venue"],
    how="left"
)

In [83]:
pd.set_option("display.max_columns",None)
data

,match_id,player,runs,balls,fours,sixes,strike_rate,runs_conceded,balls_bowled,wickets,overs,economy,fielding_points,batting_points,batting_bonus,sr_bonus,wicket_bonus,eco_bonus,lbw_bowled_bonus,bowling_points,maiden_points,fantasy_points,team,opponent,venue,city,toss_winner,toss_decision,stage,season,date,player_match_number,last3_avg_points,last5_avg_points,last10_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,pitch_type,venue_avg_points,venue_run_factor,batting_contribution_ratio,bowling_contribution_ratio,player_role,last10_std_points,player_consistency_index,form_momentum,bat_pos,boundary_percentage,bat_pos_per_match
0,548341,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,24.0,2.0,4.000000,8.000000,0.0,0.0,0,0,0,0,8.0,50.0,0.0,58.0,Deccan Chargers,Pune Warriors,Subrata Roy Sahara Stadium,Pune,Deccan Chargers,bat,Unknown,2012,2012-04-26,1,NaN,NaN,NaN,NaN,NaN,39.250000,balanced,58.00,0.879923,0.000000,1.000000,bowler,NaN,0.0,NaN,7.0,0.0,7.0
1,548346,A Ashish Reddy,10.0,10.0,0.0,1.0,100.0,11.0,13.0,1.0,2.166667,5.076923,0.0,12.0,0,0,0,4,0.0,25.0,0.0,41.0,Deccan Chargers,Mumbai Indians,Wankhede Stadium,Mumbai,Mumbai Indians,field,Unknown,2012,2012-04-29,2,NaN,NaN,NaN,NaN,NaN,30.000000,batting_friendly,41.00,1.035196,0.292683,0.707317,allrounder,NaN,0.0,NaN,7.0,0.6,8.0
2,548348,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,32.0,18.0,1.0,3.000000,10.666667,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Deccan Chargers,Pune Warriors,Barabati Stadium,Cuttack,Deccan Chargers,bat,Unknown,2012,2012-05-01,3,NaN,NaN,NaN,NaN,NaN,39.250000,balanced,23.00,1.027630,0.000000,1.000000,bowler,NaN,0.0,NaN,7.0,0.0,7.0
3,548352,A Ashish Reddy,3.0,3.0,0.0,0.0,100.0,16.0,12.0,1.0,2.000000,8.000000,0.0,3.0,0,0,0,0,0.0,25.0,0.0,28.0,Deccan Chargers,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Chennai Super Kings,bat,Unknown,2012,2012-05-04,4,40.666667,NaN,NaN,NaN,NaN,47.333333,spin_friendly,45.00,0.984847,0.107143,0.892857,bowler,17.502381,0.0,NaN,7.0,0.0,6.0
4,548356,A Ashish Reddy,0.0,0.0,0.0,0.0,0.0,36.0,24.0,1.0,4.000000,9.000000,0.0,0.0,0,0,0,0,8.0,25.0,0.0,33.0,Deccan Chargers,Royal Challengers Bengaluru,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bengaluru,field,Unknown,2012,2012-05-06,5,30.666667,NaN,NaN,NaN,NaN,38.714286,batting_friendly,31.75,1.016059,0.000000,1.000000,bowler,15.631165,0.0,NaN,7.0,0.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,36.0,22.0,1.0,3.666667,9.818182,0.0,0.0,0,0,0,0,0.0,25.0,0.0,25.0,Sunrisers Hyderabad,Mumbai Indians,Rajiv Gandhi International Stadium,Hyderabad,Mumbai Indians,field,Unknown,2025,2025-04-23,6,3.333333,25.6,NaN,0.0,0.8,18.500000,balanced,6.75,0.994802,0.000000,1.000000,bowler,36.004166,0.0,NaN,NaN,0.0,NaN
25121,1473480,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,27.0,18.0,0.0,3.000000,9.000000,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,Sunrisers Hyderabad,Chennai Super Kings,MA Chidambaram Stadium,Chennai,Sunrisers Hyderabad,field,Unknown,2025,2025-04-25,7,11.666667,13.6,NaN,0.0,0.4,0.000000,spin_friendly,0.00,0.984847,0.000000,0.000000,allrounder,32.204037,0.0,NaN,NaN,0.0,NaN
25122,1473488,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,42.0,24.0,1.0,4.000000,10.500000,0.0,0.0,0,0,0,-2,0.0,25.0,0.0,23.0,Sunrisers Hyderabad,Gujarat Titans,Narendra Modi Stadium,Ahmedabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-02,8,12.333333,7.0,NaN,0.0,0.2,11.500000,NaN,23.00,1.079940,0.000000,1.000000,bowler,30.937725,0.0,NaN,NaN,0.0,NaN
25123,1473492,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,30.0,18.0,0.0,3.000000,10.000000,6.0,0.0,0,0,0,-2,0.0,0.0,0.0,4.0,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad,field,Unknown,2025,2025-05-05,9,16.000000,11.6,NaN,0.0,0.4,44.500000,balanced,6.75,0.994802,-0.000000,1.000000,bowler,28.645618,0.0,NaN,NaN,0.0,NaN
25124,1473499,Zeeshan Ansari,0.0,0.0,0.0,0.0,0.0,22.0,12.0,0.0,2.000000,11.000000,0.0,0.0,0,0,0,-2,0.0,0.0,0.0,-2.0,Sunrisers Hyderabad,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Sunrisers Hyderabad,field,Unknown,2025,2025-05-19,10,9.000000,12.8,NaN,0.0,0.4,-2.000000,NaN,-2.00,1.040207,-0.000000,1.000000,bowler,27.459060,0.0,NaN,NaN,0.0,NaN

In [79]:
data.to_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/half_processed/half_prepared_data.csv",index = False)

In [69]:
full = pd.read_csv("/Users/nidhishgupta/Desktop/Dream11_Fantasy Team_Predictor/data/processed/full_req_data.csv")
full.isnull().sum()

match_id                    0
player                      0
fantasy_points              0
venue                       0
season                      0
                           ..
pitch_type_pace_friendly    0
pitch_type_spin_friendly    0
player_role_allrounder      0
player_role_batsman         0
player_role_bowler          0
Length: 62, dtype: int64

In [70]:
full

,match_id,player,fantasy_points,venue,season,player_match_number,last3_avg_points,rolling_strike_rate,rolling_wickets,opponent_avg_points,...,opponent_Sunrisers Hyderabad,toss_decision_bat,toss_decision_field,pitch_type_balanced,pitch_type_batting_friendly,pitch_type_pace_friendly,pitch_type_spin_friendly,player_role_allrounder,player_role_batsman,player_role_bowler
0,548341,A Ashish Reddy,58.0,Subrata Roy Sahara Stadium,2012,1,35.672040,80.762144,0.0,39.250000,...,False,True,False,True,False,False,False,False,False,True
1,548346,A Ashish Reddy,41.0,Wankhede Stadium,2012,2,35.672040,80.762144,0.0,30.000000,...,False,False,True,False,True,False,False,True,False,False
2,548348,A Ashish Reddy,23.0,Barabati Stadium,2012,3,35.672040,80.762144,0.0,39.250000,...,False,True,False,True,False,False,False,False,False,True
3,548352,A Ashish Reddy,28.0,MA Chidambaram Stadium,2012,4,40.666667,80.762144,0.0,47.333333,...,False,True,False,False,False,False,True,False,False,True
4,548356,A Ashish Reddy,33.0,M Chinnaswamy Stadium,2012,5,30.666667,80.762144,0.0,38.714286,...,False,False,True,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120,1473478,Zeeshan Ansari,25.0,Rajiv Gandhi International Stadium,2025,6,3.333333,0.000000,0.8,18.500000,...,False,False,True,True,False,False,False,False,False,True
25121,1473480,Zeeshan Ansari,0.0,MA Chidambaram Stadium,2025,7,11.666667,0.000000,0.4,0.000000,...,False,False,True,False,False,False,True,True,False,False
25122,1473488,Zeeshan Ansari,23.0,"Narendra Modi Stadium, Ahmedabad",2025,8,12.333333,0.000000,0.2,11.500000,...,False,False,True,True,False,False,False,False,False,True
25123,1473492,Zeeshan Ansari,4.0,Rajiv Gandhi International Stadium,2025,9,16.000000,0.000000,0.4,44.500000,...,False,False,True,True,False,False,False,False,False,True
25124,1473499,Zeeshan Ansari,-2.0,Ekana Cricket Stadium,2025,10,9.000000,0.000000,0.4,-2.000000,...,False,False,True,False,False,False,True,False,False,True